// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: vcs-auth-plugin.proto

package vcsauthpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthStepStatus int32

const (
	AuthStepStatus_AUTH_STATUS_UNKNOWN AuthStepStatus = 0
	AuthStepStatus_AUTH_CONTINUE       AuthStepStatus = 1 // Client must call ContinueAuth
	AuthStepStatus_AUTH_COMPLETE       AuthStepStatus = 2 // Flow finished successfully
	AuthStepStatus_AUTH_FAILED         AuthStepStatus = 3 // Flow aborted or failed
)

// Enum value maps for AuthStepStatus.
var (
	AuthStepStatus_name = map[int32]string{
		0: "AUTH_STATUS_UNKNOWN",
		1: "AUTH_CONTINUE",
		2: "AUTH_COMPLETE",
		3: "AUTH_FAILED",
	}
	AuthStepStatus_value = map[string]int32{
		"AUTH_STATUS_UNKNOWN": 0,
		"AUTH_CONTINUE":       1,
		"AUTH_COMPLETE":       2,
		"AUTH_FAILED":         3,
	}
)

func (x AuthStepStatus) Enum() *AuthStepStatus {
	p := new(AuthStepStatus)
	*p = x
	return p
}

func (x AuthStepStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthStepStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_vcs_auth_plugin_proto_enumTypes[0].Descriptor()
}

func (AuthStepStatus) Type() protoreflect.EnumType {
	return &file_vcs_auth_plugin_proto_enumTypes[0]
}

func (x AuthStepStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthStepStatus.Descriptor instead.
func (AuthStepStatus) EnumDescriptor() ([]byte, []int) {
	return file_vcs_auth_plugin_proto_rawDescGZIP(), []int{0}
}

type ConfigureRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PluginName     string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	GlobalSettings map[string]string      `protobuf:"bytes,2,rep,name=global_settings,json=globalSettings,proto3" json:"global_settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // System-wide settings (e.g., log level, backend URL)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_vcs_auth_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vcs_auth_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_vcs_auth_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigureRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *ConfigureRequest) GetGlobalSettings() map[string]string {
	if x != nil {
		return x.GlobalSettings
	}
	return nil
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_vcs_auth_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vcs_auth_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_vcs_auth_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigureResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigureResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type FlowDiscoveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowDiscoveryRequest) Reset() {
	*x = FlowDiscoveryRequest{}
	mi := &file_vcs_auth_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowDiscoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowDiscoveryRequest) ProtoMessage() {}

func (x *FlowDiscoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vcs_auth_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowDiscoveryRequest.ProtoReflect.Descriptor instead.
func (*FlowDiscoveryRequest) Descriptor() ([]byte, []int) {
	return file_vcs_auth_plugin_proto_rawDescGZIP(), []int{2}
}

type FlowDiscoveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flows         []*AuthFlowDefinition  `protobuf:"bytes,1,rep,name=flows,proto3" json:"flows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowDiscoveryResponse) Reset() {
	*x = FlowDiscoveryResponse{}
	mi := &file_vcs_auth_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowDiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowDiscoveryResponse) ProtoMessage() {}

func (x *FlowDiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vcs_auth_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowDiscoveryResponse.ProtoReflect.Descriptor instead.
func (*FlowDiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_vcs_auth_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *FlowDiscoveryResponse) GetFlows() []*AuthFlowDefinition {
	if x != nil {
		return x.Flows
	}
	return nil
}

type AuthFlowDefinition struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FlowId           string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`                               // Unique flow identifier (e.g., "oidc_mfa")
	Description      string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                                   // Human-readable description
	RequiredSettings []*FlowSettingDef      `protobuf:"bytes,3,rep,name=required_settings,json=requiredSettings,proto3" json:"required_settings,omitempty"` // Settings the server must provide via ConfigureFlow
	Steps            []*AuthStepDefinition  `protobuf:"bytes,4,rep,name=steps,proto3" json:"steps,omitempty"`                                               // Ordered steps in this flow
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthFlowDefinition) Reset() {
	*x = AuthFlowDefinition{}
	mi := &file_vcs_auth_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthFlowDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthFlowDefinition) ProtoMessage() {}

func (x *AuthFlowDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_vcs_auth_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthFlowDefinition.ProtoReflect.Descriptor instead.
func (*AuthFlowDefinition) Descriptor() ([]byte, []int) {
	return file_vcs_auth_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *AuthFlowDefinition) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *AuthFlowDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AuthFlowDefinition) GetRequiredSettings() []*FlowSettingDef {
	if x != nil {
		return x.RequiredSettings
	}
	return nil
}

func (x *AuthFlowDefinition) GetSteps() []*AuthStepDefinition {
	if x != nil {
		return x.Steps
	}
	return nil
}

type FlowSettingDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`                                       // Setting key (e.g., "client_id", "api_key")
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`                                   // Display label (e.g., "Password")
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                       // Human-readable description
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`                                     // Type hint: "string", "secret", "url", "boolean", "number"
	Required      bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`                            // Whether this setting is mandatory
	DefaultValue  string                 `protobuf:"bytes,6,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"` // Optional default value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowSettingDef) Reset() {
	*x = FlowSettingDef{}
	mi := &file_vcs_auth_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowSettingDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowSettingDef) ProtoMessage() {}

func (x *FlowSettingDef) ProtoReflect() protoreflect.Message {
	mi := &file_vcs_auth_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowSettingDef.ProtoReflect.Descriptor instead.
func (*FlowSettingDef) Descriptor() ([]byte, []int) {
	return file_vcs_auth_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *FlowSettingDef) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FlowSettingDef) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *FlowSettingDef) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FlowSettingDef) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FlowSettingDef) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *FlowSettingDef) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

type AuthStepDefinition struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StepId          string                 `protobuf:"bytes,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`                                                                 // Unique ID for this step (e.g., "password_entry")
	StepName        string                 `protobuf:"bytes,2,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`                                                           // Human-readable name (e.g., "Password Login")
	StepDescription string                 `protobuf:"bytes,3,opt,name=step_description,json=stepDescription,proto3" json:"step_description,omitempty"`                                      // Longer description for UI
	StepType        string                 `protobuf:"bytes,4,opt,name=step_type,json=stepType,proto3" json:"step_type,omitempty"`                                                           // Logical type (e.g., "password", "oidc_redirect", "totp")
	RequiredFields  []*FieldDefinition     `protobuf:"bytes,5,rep,name=required_fields,json=requiredFields,proto3" json:"required_fields,omitempty"`                                         // Structured input field definitions
	Metadata        map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // UI hints or extra info (e.g., redirect URL, QR code data)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthStepDefinition) Reset() {
	*x = AuthStepDefinition{}
	mi := &file_vcs_auth_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthStepDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthStepDefinition) ProtoMessage() {}

func (x *AuthStepDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_vcs_auth_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthStepDefinition.ProtoReflect.Descriptor instead.
func (*AuthStepDefinition) Descriptor() ([]byte, []int) {
	return file_vcs_auth_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *AuthStepDefinition) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *AuthStepDefinition) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *AuthStepDefinition) GetStepDescription() string {
	if x != nil {
		return x.StepDescription
	}
	return ""
}

func (x *AuthStepDefinition) GetStepType() string {
	if x != nil {
		return x.StepType
	}
	return ""
}

func (x *AuthStepDefinition) GetRequiredFields() []*FieldDefinition {
	if x != nil {
		return x.RequiredFields
	}
	return nil
}

func (x *AuthStepDefinition) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type FieldDefinition struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Key             string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`                                                // Key to be returned by client in step_data / first_step_input
	Label           string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`                                            // Display label (e.g., "Password")
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                                // Optional help text / tooltip
	Type            string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`                                              // Data type (e.g., "string", "password", "otp", "boolean")
	Required        bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`                                     // Is this field mandatory?
	ValidationRegex string                 `protobuf:"bytes,6,opt,name=validation_regex,json=validationRegex,proto3" json:"validation_regex,omitempty"` // Optional regex to validate field input
	DefaultValue    string                 `protobuf:"bytes,7,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`          // Optional default value
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FieldDefinition) Reset() {
	*x = FieldDefinition{}
	mi := &file_vcs_auth_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldDefinition) ProtoMessage() {}

func (x *FieldDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_vcs_auth_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldDefinition.ProtoReflect.Descriptor instead.
func (*FieldDefinition) Descriptor() ([]byte, []int) {
	return file_vcs_auth_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *FieldDefinition) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FieldDefinition) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *FieldDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FieldDefinition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FieldDefinition) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *FieldDefinition) GetValidationRegex() string {
	if x != nil {
		return x.ValidationRegex
	}
	return ""
}

func (x *FieldDefinition) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

type ConfigureFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`                                                                 // Which flow to configure
	Settings      map[string]string      `protobuf:"bytes,2,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Key-value pairs matching FlowSettingDef
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureFlowRequest) Reset() {
	*x = ConfigureFlowRequest{}
	mi := &file_vcs_auth_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureFlowRequest) ProtoMessage() {}

func (x *ConfigureFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vcs_auth_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureFlowRequest.ProtoReflect.Descriptor instead.
func (*ConfigureFlowRequest) Descriptor() ([]byte, []int) {
	return file_vcs_auth_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigureFlowRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *ConfigureFlowRequest) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

type ConfigureFlowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Error or confirmation message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureFlowResponse) Reset() {
	*x = ConfigureFlowResponse{}
	mi := &file_vcs_auth_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureFlowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureFlowResponse) ProtoMessage() {}

func (x *ConfigureFlowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vcs_auth_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureFlowResponse.ProtoReflect.Descriptor instead.
func (*ConfigureFlowResponse) Descriptor() ([]byte, []int) {
	return file_vcs_auth_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *ConfigureFlowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigureFlowResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StartAuthRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FlowId         string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`                                                                                                     // Which flow to start
	FirstStepInput map[string]string      `protobuf:"bytes,2,rep,name=first_step_input,json=firstStepInput,proto3" json:"first_step_input,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // User-provided fields for the first step
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartAuthRequest) Reset() {
	*x = StartAuthRequest{}
	mi := &file_vcs_auth_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAuthRequest) ProtoMessage() {}

func (x *StartAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vcs_auth_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAuthRequest.ProtoReflect.Descriptor instead.
func (*StartAuthRequest) Descriptor() ([]byte, []int) {
	return file_vcs_auth_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *StartAuthRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *StartAuthRequest) GetFirstStepInput() map[string]string {
	if x != nil {
		return x.FirstStepInput
	}
	return nil
}

type ContinueAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                                                        // Session ID from previous step
	StepData      map[string]string      `protobuf:"bytes,2,rep,name=step_data,json=stepData,proto3" json:"step_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // User-provided data for current step
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContinueAuthRequest) Reset() {
	*x = ContinueAuthRequest{}
	mi := &file_vcs_auth_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinueAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinueAuthRequest) ProtoMessage() {}

func (x *ContinueAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vcs_auth_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinueAuthRequest.ProtoReflect.Descriptor instead.
func (*ContinueAuthRequest) Descriptor() ([]byte, []int) {
	return file_vcs_auth_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *ContinueAuthRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ContinueAuthRequest) GetStepData() map[string]string {
	if x != nil {
		return x.StepData
	}
	return nil
}

type AuthStepResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Session ID to track flow state
	Status    AuthStepStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=vcsauthpb.AuthStepStatus" json:"status,omitempty"`
	// Types that are valid to be assigned to StepResult:
	//
	//	*AuthStepResponse_NextStep
	//	*AuthStepResponse_Complete
	//	*AuthStepResponse_ErrorMessage
	StepResult    isAuthStepResponse_StepResult `protobuf_oneof:"step_result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthStepResponse) Reset() {
	*x = AuthStepResponse{}
	mi := &file_vcs_auth_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthStepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthStepResponse) ProtoMessage() {}

func (x *AuthStepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vcs_auth_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthStepResponse.ProtoReflect.Descriptor instead.
func (*AuthStepResponse) Descriptor() ([]byte, []int) {
	return file_vcs_auth_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *AuthStepResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AuthStepResponse) GetStatus() AuthStepStatus {
	if x != nil {
		return x.Status
	}
	return AuthStepStatus_AUTH_STATUS_UNKNOWN
}

func (x *AuthStepResponse) GetStepResult() isAuthStepResponse_StepResult {
	if x != nil {
		return x.StepResult
	}
	return nil
}

func (x *AuthStepResponse) GetNextStep() *NextStepRequired {
	if x != nil {
		if x, ok := x.StepResult.(*AuthStepResponse_NextStep); ok {
			return x.NextStep
		}
	}
	return nil
}

func (x *AuthStepResponse) GetComplete() *LoginResult {
	if x != nil {
		if x, ok := x.StepResult.(*AuthStepResponse_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

func (x *AuthStepResponse) GetErrorMessage() string {
	if x != nil {
		if x, ok := x.StepResult.(*AuthStepResponse_ErrorMessage); ok {
			return x.ErrorMessage
		}
	}
	return ""
}

type isAuthStepResponse_StepResult interface {
	isAuthStepResponse_StepResult()
}

type AuthStepResponse_NextStep struct {
	NextStep *NextStepRequired `protobuf:"bytes,3,opt,name=next_step,json=nextStep,proto3,oneof"` // More steps required
}

type AuthStepResponse_Complete struct {
	Complete *LoginResult `protobuf:"bytes,4,opt,name=complete,proto3,oneof"` // Authentication complete
}

type AuthStepResponse_ErrorMessage struct {
	ErrorMessage string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3,oneof"` // Authentication failed
}

func (*AuthStepResponse_NextStep) isAuthStepResponse_StepResult() {}

func (*AuthStepResponse_Complete) isAuthStepResponse_StepResult() {}

func (*AuthStepResponse_ErrorMessage) isAuthStepResponse_StepResult() {}

type NextStepRequired struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StepId          string                 `protobuf:"bytes,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`                                                                 // Unique ID of next step
	StepName        string                 `protobuf:"bytes,2,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`                                                           // Human-readable name
	StepDescription string                 `protobuf:"bytes,3,opt,name=step_description,json=stepDescription,proto3" json:"step_description,omitempty"`                                      // Description for UI
	StepType        string                 `protobuf:"bytes,4,opt,name=step_type,json=stepType,proto3" json:"step_type,omitempty"`                                                           // Type of next step
	RequiredFields  []*FieldDefinition     `protobuf:"bytes,5,rep,name=required_fields,json=requiredFields,proto3" json:"required_fields,omitempty"`                                         // Fields client must provide
	Metadata        map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Step-specific metadata (e.g., OIDC redirect URL, QR code)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NextStepRequired) Reset() {
	*x = NextStepRequired{}
	mi := &file_vcs_auth_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextStepRequired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextStepRequired) ProtoMessage() {}

func (x *NextStepRequired) ProtoReflect() protoreflect.Message {
	mi := &file_vcs_auth_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextStepRequired.ProtoReflect.Descriptor instead.
func (*NextStepRequired) Descriptor() ([]byte, []int) {
	return file_vcs_auth_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *NextStepRequired) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *NextStepRequired) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *NextStepRequired) GetStepDescription() string {
	if x != nil {
		return x.StepDescription
	}
	return ""
}

func (x *NextStepRequired) GetStepType() string {
	if x != nil {
		return x.StepType
	}
	return ""
}

func (x *NextStepRequired) GetRequiredFields() []*FieldDefinition {
	if x != nil {
		return x.RequiredFields
	}
	return nil
}

func (x *NextStepRequired) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type LoginResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AvailableUnits []*UnitSelection       `protobuf:"bytes,1,rep,name=available_units,json=availableUnits,proto3" json:"available_units,omitempty"`
	AvailableRoles []uint32               `protobuf:"varint,2,rep,packed,name=available_roles,json=availableRoles,proto3" json:"available_roles,omitempty"`
	PlayerName     string                 `protobuf:"bytes,3,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	SessionToken   string                 `protobuf:"bytes,4,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"` // Session/bearer token for authenticated user
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoginResult) Reset() {
	*x = LoginResult{}
	mi := &file_vcs_auth_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResult) ProtoMessage() {}

func (x *LoginResult) ProtoReflect() protoreflect.Message {
	mi := &file_vcs_auth_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResult.ProtoReflect.Descriptor instead.
func (*LoginResult) Descriptor() ([]byte, []int) {
	return file_vcs_auth_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *LoginResult) GetAvailableUnits() []*UnitSelection {
	if x != nil {
		return x.AvailableUnits
	}
	return nil
}

func (x *LoginResult) GetAvailableRoles() []uint32 {
	if x != nil {
		return x.AvailableRoles
	}
	return nil
}

func (x *LoginResult) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *LoginResult) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type UnitSelection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitId        string                 `protobuf:"bytes,1,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	UnitName      string                 `protobuf:"bytes,2,opt,name=unit_name,json=unitName,proto3" json:"unit_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitSelection) Reset() {
	*x = UnitSelection{}
	mi := &file_vcs_auth_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitSelection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitSelection) ProtoMessage() {}

func (x *UnitSelection) ProtoReflect() protoreflect.Message {
	mi := &file_vcs_auth_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitSelection.ProtoReflect.Descriptor instead.
func (*UnitSelection) Descriptor() ([]byte, []int) {
	return file_vcs_auth_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *UnitSelection) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *UnitSelection) GetUnitName() string {
	if x != nil {
		return x.UnitName
	}
	return ""
}

var File_vcs_auth_plugin_proto protoreflect.FileDescriptor

const file_vcs_auth_plugin_proto_rawDesc = "" +
	"\n" +
	"\x15vcs-auth-plugin.proto\x12\tvcsauthpb\"\xd0\x01\n" +
	"\x10ConfigureRequest\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12X\n" +
	"\x0fglobal_settings\x18\x02 \x03(\v2/.vcsauthpb.ConfigureRequest.GlobalSettingsEntryR\x0eglobalSettings\x1aA\n" +
	"\x13GlobalSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"a\n" +
	"\x11ConfigureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\x16\n" +
	"\x14FlowDiscoveryRequest\"L\n" +
	"\x15FlowDiscoveryResponse\x123\n" +
	"\x05flows\x18\x01 \x03(\v2\x1d.vcsauthpb.AuthFlowDefinitionR\x05flows\"\xcc\x01\n" +
	"\x12AuthFlowDefinition\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12F\n" +
	"\x11required_settings\x18\x03 \x03(\v2\x19.vcsauthpb.FlowSettingDefR\x10requiredSettings\x123\n" +
	"\x05steps\x18\x04 \x03(\v2\x1d.vcsauthpb.AuthStepDefinitionR\x05steps\"\xaf\x01\n" +
	"\x0eFlowSettingDef\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12#\n" +
	"\rdefault_value\x18\x06 \x01(\tR\fdefaultValue\"\xdd\x02\n" +
	"\x12AuthStepDefinition\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\tR\x06stepId\x12\x1b\n" +
	"\tstep_name\x18\x02 \x01(\tR\bstepName\x12)\n" +
	"\x10step_description\x18\x03 \x01(\tR\x0fstepDescription\x12\x1b\n" +
	"\tstep_type\x18\x04 \x01(\tR\bstepType\x12C\n" +
	"\x0frequired_fields\x18\x05 \x03(\v2\x1a.vcsauthpb.FieldDefinitionR\x0erequiredFields\x12G\n" +
	"\bmetadata\x18\x06 \x03(\v2+.vcsauthpb.AuthStepDefinition.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdb\x01\n" +
	"\x0fFieldDefinition\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12)\n" +
	"\x10validation_regex\x18\x06 \x01(\tR\x0fvalidationRegex\x12#\n" +
	"\rdefault_value\x18\a \x01(\tR\fdefaultValue\"\xb7\x01\n" +
	"\x14ConfigureFlowRequest\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\x12I\n" +
	"\bsettings\x18\x02 \x03(\v2-.vcsauthpb.ConfigureFlowRequest.SettingsEntryR\bsettings\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\x15ConfigureFlowResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc9\x01\n" +
	"\x10StartAuthRequest\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\x12Y\n" +
	"\x10first_step_input\x18\x02 \x03(\v2/.vcsauthpb.StartAuthRequest.FirstStepInputEntryR\x0efirstStepInput\x1aA\n" +
	"\x13FirstStepInputEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbc\x01\n" +
	"\x13ContinueAuthRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12I\n" +
	"\tstep_data\x18\x02 \x03(\v2,.vcsauthpb.ContinueAuthRequest.StepDataEntryR\bstepData\x1a;\n" +
	"\rStepDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8c\x02\n" +
	"\x10AuthStepResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.vcsauthpb.AuthStepStatusR\x06status\x12:\n" +
	"\tnext_step\x18\x03 \x01(\v2\x1b.vcsauthpb.NextStepRequiredH\x00R\bnextStep\x124\n" +
	"\bcomplete\x18\x04 \x01(\v2\x16.vcsauthpb.LoginResultH\x00R\bcomplete\x12%\n" +
	"\rerror_message\x18\x05 \x01(\tH\x00R\ferrorMessageB\r\n" +
	"\vstep_result\"\xd9\x02\n" +
	"\x10NextStepRequired\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\tR\x06stepId\x12\x1b\n" +
	"\tstep_name\x18\x02 \x01(\tR\bstepName\x12)\n" +
	"\x10step_description\x18\x03 \x01(\tR\x0fstepDescription\x12\x1b\n" +
	"\tstep_type\x18\x04 \x01(\tR\bstepType\x12C\n" +
	"\x0frequired_fields\x18\x05 \x03(\v2\x1a.vcsauthpb.FieldDefinitionR\x0erequiredFields\x12E\n" +
	"\bmetadata\x18\x06 \x03(\v2).vcsauthpb.NextStepRequired.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbf\x01\n" +
	"\vLoginResult\x12A\n" +
	"\x0favailable_units\x18\x01 \x03(\v2\x18.vcsauthpb.UnitSelectionR\x0eavailableUnits\x12'\n" +
	"\x0favailable_roles\x18\x02 \x03(\rR\x0eavailableRoles\x12\x1f\n" +
	"\vplayer_name\x18\x03 \x01(\tR\n" +
	"playerName\x12#\n" +
	"\rsession_token\x18\x04 \x01(\tR\fsessionToken\"E\n" +
	"\rUnitSelection\x12\x17\n" +
	"\aunit_id\x18\x01 \x01(\tR\x06unitId\x12\x1b\n" +
	"\tunit_name\x18\x02 \x01(\tR\bunitName*`\n" +
	"\x0eAuthStepStatus\x12\x17\n" +
	"\x13AUTH_STATUS_UNKNOWN\x10\x00\x12\x11\n" +
	"\rAUTH_CONTINUE\x10\x01\x12\x11\n" +
	"\rAUTH_COMPLETE\x10\x02\x12\x0f\n" +
	"\vAUTH_FAILED\x10\x032\x9b\x03\n" +
	"\x11AuthPluginService\x12F\n" +
	"\tConfigure\x12\x1b.vcsauthpb.ConfigureRequest\x1a\x1c.vcsauthpb.ConfigureResponse\x12V\n" +
	"\x11GetSupportedFlows\x12\x1f.vcsauthpb.FlowDiscoveryRequest\x1a .vcsauthpb.FlowDiscoveryResponse\x12R\n" +
	"\rConfigureFlow\x12\x1f.vcsauthpb.ConfigureFlowRequest\x1a .vcsauthpb.ConfigureFlowResponse\x12E\n" +
	"\tStartAuth\x12\x1b.vcsauthpb.StartAuthRequest\x1a\x1b.vcsauthpb.AuthStepResponse\x12K\n" +
	"\fContinueAuth\x12\x1e.vcsauthpb.ContinueAuthRequest\x1a\x1b.vcsauthpb.AuthStepResponseB/Z-github.com/FPGSchiba/vcs-srs-server/vcsauthpbb\x06proto3"

var (
	file_vcs_auth_plugin_proto_rawDescOnce sync.Once
	file_vcs_auth_plugin_proto_rawDescData []byte
)

func file_vcs_auth_plugin_proto_rawDescGZIP() []byte {
	file_vcs_auth_plugin_proto_rawDescOnce.Do(func() {
		file_vcs_auth_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vcs_auth_plugin_proto_rawDesc), len(file_vcs_auth_plugin_proto_rawDesc)))
	})
	return file_vcs_auth_plugin_proto_rawDescData
}

var file_vcs_auth_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vcs_auth_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_vcs_auth_plugin_proto_goTypes = []any{
	(AuthStepStatus)(0),           // 0: vcsauthpb.AuthStepStatus
	(*ConfigureRequest)(nil),      // 1: vcsauthpb.ConfigureRequest
	(*ConfigureResponse)(nil),     // 2: vcsauthpb.ConfigureResponse
	(*FlowDiscoveryRequest)(nil),  // 3: vcsauthpb.FlowDiscoveryRequest
	(*FlowDiscoveryResponse)(nil), // 4: vcsauthpb.FlowDiscoveryResponse
	(*AuthFlowDefinition)(nil),    // 5: vcsauthpb.AuthFlowDefinition
	(*FlowSettingDef)(nil),        // 6: vcsauthpb.FlowSettingDef
	(*AuthStepDefinition)(nil),    // 7: vcsauthpb.AuthStepDefinition
	(*FieldDefinition)(nil),       // 8: vcsauthpb.FieldDefinition
	(*ConfigureFlowRequest)(nil),  // 9: vcsauthpb.ConfigureFlowRequest
	(*ConfigureFlowResponse)(nil), // 10: vcsauthpb.ConfigureFlowResponse
	(*StartAuthRequest)(nil),      // 11: vcsauthpb.StartAuthRequest
	(*ContinueAuthRequest)(nil),   // 12: vcsauthpb.ContinueAuthRequest
	(*AuthStepResponse)(nil),      // 13: vcsauthpb.AuthStepResponse
	(*NextStepRequired)(nil),      // 14: vcsauthpb.NextStepRequired
	(*LoginResult)(nil),           // 15: vcsauthpb.LoginResult
	(*UnitSelection)(nil),         // 16: vcsauthpb.UnitSelection
	nil,                           // 17: vcsauthpb.ConfigureRequest.GlobalSettingsEntry
	nil,                           // 18: vcsauthpb.AuthStepDefinition.MetadataEntry
	nil,                           // 19: vcsauthpb.ConfigureFlowRequest.SettingsEntry
	nil,                           // 20: vcsauthpb.StartAuthRequest.FirstStepInputEntry
	nil,                           // 21: vcsauthpb.ContinueAuthRequest.StepDataEntry
	nil,                           // 22: vcsauthpb.NextStepRequired.MetadataEntry
}
var file_vcs_auth_plugin_proto_depIdxs = []int32{
	17, // 0: vcsauthpb.ConfigureRequest.global_settings:type_name -> vcsauthpb.ConfigureRequest.GlobalSettingsEntry
	5,  // 1: vcsauthpb.FlowDiscoveryResponse.flows:type_name -> vcsauthpb.AuthFlowDefinition
	6,  // 2: vcsauthpb.AuthFlowDefinition.required_settings:type_name -> vcsauthpb.FlowSettingDef
	7,  // 3: vcsauthpb.AuthFlowDefinition.steps:type_name -> vcsauthpb.AuthStepDefinition
	8,  // 4: vcsauthpb.AuthStepDefinition.required_fields:type_name -> vcsauthpb.FieldDefinition
	18, // 5: vcsauthpb.AuthStepDefinition.metadata:type_name -> vcsauthpb.AuthStepDefinition.MetadataEntry
	19, // 6: vcsauthpb.ConfigureFlowRequest.settings:type_name -> vcsauthpb.ConfigureFlowRequest.SettingsEntry
	20, // 7: vcsauthpb.StartAuthRequest.first_step_input:type_name -> vcsauthpb.StartAuthRequest.FirstStepInputEntry
	21, // 8: vcsauthpb.ContinueAuthRequest.step_data:type_name -> vcsauthpb.ContinueAuthRequest.StepDataEntry
	0,  // 9: vcsauthpb.AuthStepResponse.status:type_name -> vcsauthpb.AuthStepStatus
	14, // 10: vcsauthpb.AuthStepResponse.next_step:type_name -> vcsauthpb.NextStepRequired
	15, // 11: vcsauthpb.AuthStepResponse.complete:type_name -> vcsauthpb.LoginResult
	8,  // 12: vcsauthpb.NextStepRequired.required_fields:type_name -> vcsauthpb.FieldDefinition
	22, // 13: vcsauthpb.NextStepRequired.metadata:type_name -> vcsauthpb.NextStepRequired.MetadataEntry
	16, // 14: vcsauthpb.LoginResult.available_units:type_name -> vcsauthpb.UnitSelection
	1,  // 15: vcsauthpb.AuthPluginService.Configure:input_type -> vcsauthpb.ConfigureRequest
	3,  // 16: vcsauthpb.AuthPluginService.GetSupportedFlows:input_type -> vcsauthpb.FlowDiscoveryRequest
	9,  // 17: vcsauthpb.AuthPluginService.ConfigureFlow:input_type -> vcsauthpb.ConfigureFlowRequest
	11, // 18: vcsauthpb.AuthPluginService.StartAuth:input_type -> vcsauthpb.StartAuthRequest
	12, // 19: vcsauthpb.AuthPluginService.ContinueAuth:input_type -> vcsauthpb.ContinueAuthRequest
	2,  // 20: vcsauthpb.AuthPluginService.Configure:output_type -> vcsauthpb.ConfigureResponse
	4,  // 21: vcsauthpb.AuthPluginService.GetSupportedFlows:output_type -> vcsauthpb.FlowDiscoveryResponse
	10, // 22: vcsauthpb.AuthPluginService.ConfigureFlow:output_type -> vcsauthpb.ConfigureFlowResponse
	13, // 23: vcsauthpb.AuthPluginService.StartAuth:output_type -> vcsauthpb.AuthStepResponse
	13, // 24: vcsauthpb.AuthPluginService.ContinueAuth:output_type -> vcsauthpb.AuthStepResponse
	20, // [20:25] is the sub-list for method output_type
	15, // [15:20] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_vcs_auth_plugin_proto_init() }
func file_vcs_auth_plugin_proto_init() {
	if File_vcs_auth_plugin_proto != nil {
		return
	}
	file_vcs_auth_plugin_proto_msgTypes[12].OneofWrappers = []any{
		(*AuthStepResponse_NextStep)(nil),
		(*AuthStepResponse_Complete)(nil),
		(*AuthStepResponse_ErrorMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vcs_auth_plugin_proto_rawDesc), len(file_vcs_auth_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vcs_auth_plugin_proto_goTypes,
		DependencyIndexes: file_vcs_auth_plugin_proto_depIdxs,
		EnumInfos:         file_vcs_auth_plugin_proto_enumTypes,
		MessageInfos:      file_vcs_auth_plugin_proto_msgTypes,
	}.Build()
	File_vcs_auth_plugin_proto = out.File
	file_vcs_auth_plugin_proto_goTypes = nil
	file_vcs_auth_plugin_proto_depIdxs = nil
}
