// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.30.2
// source: vcs-auth-plugin.proto

package vcsauthpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthPluginService_Configure_FullMethodName         = "/vcsauthpb.AuthPluginService/Configure"
	AuthPluginService_GetSupportedFlows_FullMethodName = "/vcsauthpb.AuthPluginService/GetSupportedFlows"
	AuthPluginService_ConfigureFlow_FullMethodName     = "/vcsauthpb.AuthPluginService/ConfigureFlow"
	AuthPluginService_StartAuth_FullMethodName         = "/vcsauthpb.AuthPluginService/StartAuth"
	AuthPluginService_ContinueAuth_FullMethodName      = "/vcsauthpb.AuthPluginService/ContinueAuth"
)

// AuthPluginServiceClient is the client API for AuthPluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthPluginServiceClient interface {
	// Configure the plugin with global/system-level settings
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
	// Discover which authentication flows this plugin provides
	GetSupportedFlows(ctx context.Context, in *FlowDiscoveryRequest, opts ...grpc.CallOption) (*FlowDiscoveryResponse, error)
	// Provide flow-specific settings (e.g., OIDC client secrets, API keys)
	ConfigureFlow(ctx context.Context, in *ConfigureFlowRequest, opts ...grpc.CallOption) (*ConfigureFlowResponse, error)
	// Start a new authentication flow
	StartAuth(ctx context.Context, in *StartAuthRequest, opts ...grpc.CallOption) (*AuthStepResponse, error)
	// Continue an existing authentication flow
	ContinueAuth(ctx context.Context, in *ContinueAuthRequest, opts ...grpc.CallOption) (*AuthStepResponse, error)
}

type authPluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthPluginServiceClient(cc grpc.ClientConnInterface) AuthPluginServiceClient {
	return &authPluginServiceClient{cc}
}

func (c *authPluginServiceClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, AuthPluginService_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authPluginServiceClient) GetSupportedFlows(ctx context.Context, in *FlowDiscoveryRequest, opts ...grpc.CallOption) (*FlowDiscoveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlowDiscoveryResponse)
	err := c.cc.Invoke(ctx, AuthPluginService_GetSupportedFlows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authPluginServiceClient) ConfigureFlow(ctx context.Context, in *ConfigureFlowRequest, opts ...grpc.CallOption) (*ConfigureFlowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureFlowResponse)
	err := c.cc.Invoke(ctx, AuthPluginService_ConfigureFlow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authPluginServiceClient) StartAuth(ctx context.Context, in *StartAuthRequest, opts ...grpc.CallOption) (*AuthStepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthStepResponse)
	err := c.cc.Invoke(ctx, AuthPluginService_StartAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authPluginServiceClient) ContinueAuth(ctx context.Context, in *ContinueAuthRequest, opts ...grpc.CallOption) (*AuthStepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthStepResponse)
	err := c.cc.Invoke(ctx, AuthPluginService_ContinueAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthPluginServiceServer is the server API for AuthPluginService service.
// All implementations must embed UnimplementedAuthPluginServiceServer
// for forward compatibility.
type AuthPluginServiceServer interface {
	// Configure the plugin with global/system-level settings
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	// Discover which authentication flows this plugin provides
	GetSupportedFlows(context.Context, *FlowDiscoveryRequest) (*FlowDiscoveryResponse, error)
	// Provide flow-specific settings (e.g., OIDC client secrets, API keys)
	ConfigureFlow(context.Context, *ConfigureFlowRequest) (*ConfigureFlowResponse, error)
	// Start a new authentication flow
	StartAuth(context.Context, *StartAuthRequest) (*AuthStepResponse, error)
	// Continue an existing authentication flow
	ContinueAuth(context.Context, *ContinueAuthRequest) (*AuthStepResponse, error)
	mustEmbedUnimplementedAuthPluginServiceServer()
}

// UnimplementedAuthPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthPluginServiceServer struct{}

func (UnimplementedAuthPluginServiceServer) Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedAuthPluginServiceServer) GetSupportedFlows(context.Context, *FlowDiscoveryRequest) (*FlowDiscoveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSupportedFlows not implemented")
}
func (UnimplementedAuthPluginServiceServer) ConfigureFlow(context.Context, *ConfigureFlowRequest) (*ConfigureFlowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureFlow not implemented")
}
func (UnimplementedAuthPluginServiceServer) StartAuth(context.Context, *StartAuthRequest) (*AuthStepResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartAuth not implemented")
}
func (UnimplementedAuthPluginServiceServer) ContinueAuth(context.Context, *ContinueAuthRequest) (*AuthStepResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ContinueAuth not implemented")
}
func (UnimplementedAuthPluginServiceServer) mustEmbedUnimplementedAuthPluginServiceServer() {}
func (UnimplementedAuthPluginServiceServer) testEmbeddedByValue()                           {}

// UnsafeAuthPluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthPluginServiceServer will
// result in compilation errors.
type UnsafeAuthPluginServiceServer interface {
	mustEmbedUnimplementedAuthPluginServiceServer()
}

func RegisterAuthPluginServiceServer(s grpc.ServiceRegistrar, srv AuthPluginServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthPluginService_ServiceDesc, srv)
}

func _AuthPluginService_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthPluginServiceServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthPluginService_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthPluginServiceServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthPluginService_GetSupportedFlows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlowDiscoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthPluginServiceServer).GetSupportedFlows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthPluginService_GetSupportedFlows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthPluginServiceServer).GetSupportedFlows(ctx, req.(*FlowDiscoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthPluginService_ConfigureFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthPluginServiceServer).ConfigureFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthPluginService_ConfigureFlow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthPluginServiceServer).ConfigureFlow(ctx, req.(*ConfigureFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthPluginService_StartAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthPluginServiceServer).StartAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthPluginService_StartAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthPluginServiceServer).StartAuth(ctx, req.(*StartAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthPluginService_ContinueAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContinueAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthPluginServiceServer).ContinueAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthPluginService_ContinueAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthPluginServiceServer).ContinueAuth(ctx, req.(*ContinueAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthPluginService_ServiceDesc is the grpc.ServiceDesc for AuthPluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthPluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vcsauthpb.AuthPluginService",
	HandlerType: (*AuthPluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Configure",
			Handler:    _AuthPluginService_Configure_Handler,
		},
		{
			MethodName: "GetSupportedFlows",
			Handler:    _AuthPluginService_GetSupportedFlows_Handler,
		},
		{
			MethodName: "ConfigureFlow",
			Handler:    _AuthPluginService_ConfigureFlow_Handler,
		},
		{
			MethodName: "StartAuth",
			Handler:    _AuthPluginService_StartAuth_Handler,
		},
		{
			MethodName: "ContinueAuth",
			Handler:    _AuthPluginService_ContinueAuth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vcs-auth-plugin.proto",
}
