[package]
name = "vngd-srs-server"
version = "0.1.0"
edition = "2021"

[dependencies]
phf = { version = "0.11", features = ["macros"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.19"
