package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/FPGSchiba/vcs-srs-server/graphql/generated"
)

// UpdateGeneralSettings is the resolver for the updateGeneralSettings field.
func (r *mutationResolver) UpdateGeneralSettings(ctx context.Context, input generated.GeneralSettingsInput) (*generated.MutationResult, error) {
	panic(fmt.Errorf("not implemented: UpdateGeneralSettings - updateGeneralSettings"))
}

// UpdateSecuritySettings is the resolver for the updateSecuritySettings field.
func (r *mutationResolver) UpdateSecuritySettings(ctx context.Context, input generated.SecuritySettingsInput) (*generated.MutationResult, error) {
	panic(fmt.Errorf("not implemented: UpdateSecuritySettings - updateSecuritySettings"))
}

// UpdateVoiceControlSettings is the resolver for the updateVoiceControlSettings field.
func (r *mutationResolver) UpdateVoiceControlSettings(ctx context.Context, input generated.VoiceControlSettingsInput) (*generated.MutationResult, error) {
	panic(fmt.Errorf("not implemented: UpdateVoiceControlSettings - updateVoiceControlSettings"))
}

// UpdateFrequencySettings is the resolver for the updateFrequencySettings field.
func (r *mutationResolver) UpdateFrequencySettings(ctx context.Context, input generated.FrequencySettingsInput) (*generated.MutationResult, error) {
	panic(fmt.Errorf("not implemented: UpdateFrequencySettings - updateFrequencySettings"))
}

// UpdateCoalitions is the resolver for the updateCoalitions field.
func (r *mutationResolver) UpdateCoalitions(ctx context.Context, coalitions []*generated.CoalitionInput) (*generated.MutationResult, error) {
	panic(fmt.Errorf("not implemented: UpdateCoalitions - updateCoalitions"))
}

// UpdateServerSettings is the resolver for the updateServerSettings field.
func (r *mutationResolver) UpdateServerSettings(ctx context.Context, input generated.ServerSettingsInput) (*generated.MutationResult, error) {
	panic(fmt.Errorf("not implemented: UpdateServerSettings - updateServerSettings"))
}

// StartServer is the resolver for the startServer field.
func (r *mutationResolver) StartServer(ctx context.Context) (*generated.MutationResult, error) {
	panic(fmt.Errorf("not implemented: StartServer - startServer"))
}

// StopServer is the resolver for the stopServer field.
func (r *mutationResolver) StopServer(ctx context.Context) (*generated.MutationResult, error) {
	panic(fmt.Errorf("not implemented: StopServer - stopServer"))
}

// KickClient is the resolver for the kickClient field.
func (r *mutationResolver) KickClient(ctx context.Context, clientID string, reason string) (*generated.MutationResult, error) {
	panic(fmt.Errorf("not implemented: KickClient - kickClient"))
}

// BanClient is the resolver for the banClient field.
func (r *mutationResolver) BanClient(ctx context.Context, clientID string, reason string) (*generated.MutationResult, error) {
	panic(fmt.Errorf("not implemented: BanClient - banClient"))
}

// UnbanClient is the resolver for the unbanClient field.
func (r *mutationResolver) UnbanClient(ctx context.Context, clientID string) (*generated.MutationResult, error) {
	panic(fmt.Errorf("not implemented: UnbanClient - unbanClient"))
}

// MuteClient is the resolver for the muteClient field.
func (r *mutationResolver) MuteClient(ctx context.Context, clientID string) (*generated.MutationResult, error) {
	panic(fmt.Errorf("not implemented: MuteClient - muteClient"))
}

// UnmuteClient is the resolver for the unmuteClient field.
func (r *mutationResolver) UnmuteClient(ctx context.Context, clientID string) (*generated.MutationResult, error) {
	panic(fmt.Errorf("not implemented: UnmuteClient - unmuteClient"))
}

// SystemInfo is the resolver for the systemInfo field.
func (r *queryResolver) SystemInfo(ctx context.Context) (*generated.SystemInfo, error) {
	panic(fmt.Errorf("not implemented: SystemInfo - systemInfo"))
}

// Clients is the resolver for the clients field.
func (r *queryResolver) Clients(ctx context.Context) ([]*generated.Client, error) {
	panic(fmt.Errorf("not implemented: Clients - clients"))
}

// BannedClients is the resolver for the bannedClients field.
func (r *queryResolver) BannedClients(ctx context.Context) ([]*generated.BannedClient, error) {
	panic(fmt.Errorf("not implemented: BannedClients - bannedClients"))
}

// Settings is the resolver for the settings field.
func (r *queryResolver) Settings(ctx context.Context) (*generated.Settings, error) {
	panic(fmt.Errorf("not implemented: Settings - settings"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
