// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.30.2
// source: control.proto

package voicecontrolpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VoiceControlService_RegisterVoiceServer_FullMethodName      = "/voicecontrolpb.VoiceControlService/RegisterVoiceServer"
	VoiceControlService_SendHeartbeat_FullMethodName            = "/voicecontrolpb.VoiceControlService/SendHeartbeat"
	VoiceControlService_ReportClientConnected_FullMethodName    = "/voicecontrolpb.VoiceControlService/ReportClientConnected"
	VoiceControlService_ReportClientDisconnected_FullMethodName = "/voicecontrolpb.VoiceControlService/ReportClientDisconnected"
	VoiceControlService_ReportFrequencyChange_FullMethodName    = "/voicecontrolpb.VoiceControlService/ReportFrequencyChange"
	VoiceControlService_EstablishStream_FullMethodName          = "/voicecontrolpb.VoiceControlService/EstablishStream"
)

// VoiceControlServiceClient is the client API for VoiceControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition for Voice Server <-> Control Server communication
type VoiceControlServiceClient interface {
	// Initial registration and reporting
	RegisterVoiceServer(ctx context.Context, in *RegisterVoiceServerRequest, opts ...grpc.CallOption) (*RegisterVoiceServerResponse, error)
	SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	ReportClientConnected(ctx context.Context, in *ClientConnectedRequest, opts ...grpc.CallOption) (*ClientConnectedResponse, error)
	ReportClientDisconnected(ctx context.Context, in *ClientDisconnectedRequest, opts ...grpc.CallOption) (*ClientDisconnectedResponse, error)
	ReportFrequencyChange(ctx context.Context, in *FrequencyChangeRequest, opts ...grpc.CallOption) (*FrequencyChangeResponse, error)
	// Stream for control commands (Control -> Voice) with event IDs
	EstablishStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlResponse, ControlMessage], error)
}

type voiceControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVoiceControlServiceClient(cc grpc.ClientConnInterface) VoiceControlServiceClient {
	return &voiceControlServiceClient{cc}
}

func (c *voiceControlServiceClient) RegisterVoiceServer(ctx context.Context, in *RegisterVoiceServerRequest, opts ...grpc.CallOption) (*RegisterVoiceServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterVoiceServerResponse)
	err := c.cc.Invoke(ctx, VoiceControlService_RegisterVoiceServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceControlServiceClient) SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, VoiceControlService_SendHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceControlServiceClient) ReportClientConnected(ctx context.Context, in *ClientConnectedRequest, opts ...grpc.CallOption) (*ClientConnectedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientConnectedResponse)
	err := c.cc.Invoke(ctx, VoiceControlService_ReportClientConnected_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceControlServiceClient) ReportClientDisconnected(ctx context.Context, in *ClientDisconnectedRequest, opts ...grpc.CallOption) (*ClientDisconnectedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientDisconnectedResponse)
	err := c.cc.Invoke(ctx, VoiceControlService_ReportClientDisconnected_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceControlServiceClient) ReportFrequencyChange(ctx context.Context, in *FrequencyChangeRequest, opts ...grpc.CallOption) (*FrequencyChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FrequencyChangeResponse)
	err := c.cc.Invoke(ctx, VoiceControlService_ReportFrequencyChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceControlServiceClient) EstablishStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlResponse, ControlMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VoiceControlService_ServiceDesc.Streams[0], VoiceControlService_EstablishStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ControlResponse, ControlMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VoiceControlService_EstablishStreamClient = grpc.BidiStreamingClient[ControlResponse, ControlMessage]

// VoiceControlServiceServer is the server API for VoiceControlService service.
// All implementations must embed UnimplementedVoiceControlServiceServer
// for forward compatibility.
//
// Service definition for Voice Server <-> Control Server communication
type VoiceControlServiceServer interface {
	// Initial registration and reporting
	RegisterVoiceServer(context.Context, *RegisterVoiceServerRequest) (*RegisterVoiceServerResponse, error)
	SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	ReportClientConnected(context.Context, *ClientConnectedRequest) (*ClientConnectedResponse, error)
	ReportClientDisconnected(context.Context, *ClientDisconnectedRequest) (*ClientDisconnectedResponse, error)
	ReportFrequencyChange(context.Context, *FrequencyChangeRequest) (*FrequencyChangeResponse, error)
	// Stream for control commands (Control -> Voice) with event IDs
	EstablishStream(grpc.BidiStreamingServer[ControlResponse, ControlMessage]) error
	mustEmbedUnimplementedVoiceControlServiceServer()
}

// UnimplementedVoiceControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVoiceControlServiceServer struct{}

func (UnimplementedVoiceControlServiceServer) RegisterVoiceServer(context.Context, *RegisterVoiceServerRequest) (*RegisterVoiceServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterVoiceServer not implemented")
}
func (UnimplementedVoiceControlServiceServer) SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedVoiceControlServiceServer) ReportClientConnected(context.Context, *ClientConnectedRequest) (*ClientConnectedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportClientConnected not implemented")
}
func (UnimplementedVoiceControlServiceServer) ReportClientDisconnected(context.Context, *ClientDisconnectedRequest) (*ClientDisconnectedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportClientDisconnected not implemented")
}
func (UnimplementedVoiceControlServiceServer) ReportFrequencyChange(context.Context, *FrequencyChangeRequest) (*FrequencyChangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportFrequencyChange not implemented")
}
func (UnimplementedVoiceControlServiceServer) EstablishStream(grpc.BidiStreamingServer[ControlResponse, ControlMessage]) error {
	return status.Error(codes.Unimplemented, "method EstablishStream not implemented")
}
func (UnimplementedVoiceControlServiceServer) mustEmbedUnimplementedVoiceControlServiceServer() {}
func (UnimplementedVoiceControlServiceServer) testEmbeddedByValue()                             {}

// UnsafeVoiceControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoiceControlServiceServer will
// result in compilation errors.
type UnsafeVoiceControlServiceServer interface {
	mustEmbedUnimplementedVoiceControlServiceServer()
}

func RegisterVoiceControlServiceServer(s grpc.ServiceRegistrar, srv VoiceControlServiceServer) {
	// If the following call panics, it indicates UnimplementedVoiceControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VoiceControlService_ServiceDesc, srv)
}

func _VoiceControlService_RegisterVoiceServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterVoiceServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceControlServiceServer).RegisterVoiceServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceControlService_RegisterVoiceServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceControlServiceServer).RegisterVoiceServer(ctx, req.(*RegisterVoiceServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceControlService_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceControlServiceServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceControlService_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceControlServiceServer).SendHeartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceControlService_ReportClientConnected_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientConnectedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceControlServiceServer).ReportClientConnected(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceControlService_ReportClientConnected_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceControlServiceServer).ReportClientConnected(ctx, req.(*ClientConnectedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceControlService_ReportClientDisconnected_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientDisconnectedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceControlServiceServer).ReportClientDisconnected(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceControlService_ReportClientDisconnected_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceControlServiceServer).ReportClientDisconnected(ctx, req.(*ClientDisconnectedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceControlService_ReportFrequencyChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FrequencyChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceControlServiceServer).ReportFrequencyChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoiceControlService_ReportFrequencyChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceControlServiceServer).ReportFrequencyChange(ctx, req.(*FrequencyChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoiceControlService_EstablishStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VoiceControlServiceServer).EstablishStream(&grpc.GenericServerStream[ControlResponse, ControlMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VoiceControlService_EstablishStreamServer = grpc.BidiStreamingServer[ControlResponse, ControlMessage]

// VoiceControlService_ServiceDesc is the grpc.ServiceDesc for VoiceControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoiceControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voicecontrolpb.VoiceControlService",
	HandlerType: (*VoiceControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterVoiceServer",
			Handler:    _VoiceControlService_RegisterVoiceServer_Handler,
		},
		{
			MethodName: "SendHeartbeat",
			Handler:    _VoiceControlService_SendHeartbeat_Handler,
		},
		{
			MethodName: "ReportClientConnected",
			Handler:    _VoiceControlService_ReportClientConnected_Handler,
		},
		{
			MethodName: "ReportClientDisconnected",
			Handler:    _VoiceControlService_ReportClientDisconnected_Handler,
		},
		{
			MethodName: "ReportFrequencyChange",
			Handler:    _VoiceControlService_ReportFrequencyChange_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EstablishStream",
			Handler:       _VoiceControlService_EstablishStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "control.proto",
}
