// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: control.proto

package voicecontrolpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DisconnectReason int32

const (
	DisconnectReason_CLIENT_DISCONNECT      DisconnectReason = 0
	DisconnectReason_KICKED                 DisconnectReason = 1
	DisconnectReason_TIMEOUT                DisconnectReason = 2
	DisconnectReason_SERVER_SHUTDOWN        DisconnectReason = 3
	DisconnectReason_FREQUENCY_REASSIGNMENT DisconnectReason = 4
)

// Enum value maps for DisconnectReason.
var (
	DisconnectReason_name = map[int32]string{
		0: "CLIENT_DISCONNECT",
		1: "KICKED",
		2: "TIMEOUT",
		3: "SERVER_SHUTDOWN",
		4: "FREQUENCY_REASSIGNMENT",
	}
	DisconnectReason_value = map[string]int32{
		"CLIENT_DISCONNECT":      0,
		"KICKED":                 1,
		"TIMEOUT":                2,
		"SERVER_SHUTDOWN":        3,
		"FREQUENCY_REASSIGNMENT": 4,
	}
)

func (x DisconnectReason) Enum() *DisconnectReason {
	p := new(DisconnectReason)
	*p = x
	return p
}

func (x DisconnectReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DisconnectReason) Descriptor() protoreflect.EnumDescriptor {
	return file_control_proto_enumTypes[0].Descriptor()
}

func (DisconnectReason) Type() protoreflect.EnumType {
	return &file_control_proto_enumTypes[0]
}

func (x DisconnectReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DisconnectReason.Descriptor instead.
func (DisconnectReason) EnumDescriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

type CommandType int32

const (
	CommandType_NO_COMMAND       CommandType = 0
	CommandType_KICK_CLIENT      CommandType = 1
	CommandType_CHANGE_FREQUENCY CommandType = 2
	CommandType_UPDATE_CONFIG    CommandType = 3
	CommandType_SHUTDOWN         CommandType = 4
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "NO_COMMAND",
		1: "KICK_CLIENT",
		2: "CHANGE_FREQUENCY",
		3: "UPDATE_CONFIG",
		4: "SHUTDOWN",
	}
	CommandType_value = map[string]int32{
		"NO_COMMAND":       0,
		"KICK_CLIENT":      1,
		"CHANGE_FREQUENCY": 2,
		"UPDATE_CONFIG":    3,
		"SHUTDOWN":         4,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_control_proto_enumTypes[1].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_control_proto_enumTypes[1]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

type ClientDelta_Type int32

const (
	ClientDelta_JOINED        ClientDelta_Type = 0
	ClientDelta_LEFT          ClientDelta_Type = 1
	ClientDelta_INFO_UPDATED  ClientDelta_Type = 2
	ClientDelta_RADIO_UPDATED ClientDelta_Type = 3
	ClientDelta_MUTED         ClientDelta_Type = 4
	ClientDelta_UNMUTED       ClientDelta_Type = 5
)

// Enum value maps for ClientDelta_Type.
var (
	ClientDelta_Type_name = map[int32]string{
		0: "JOINED",
		1: "LEFT",
		2: "INFO_UPDATED",
		3: "RADIO_UPDATED",
		4: "MUTED",
		5: "UNMUTED",
	}
	ClientDelta_Type_value = map[string]int32{
		"JOINED":        0,
		"LEFT":          1,
		"INFO_UPDATED":  2,
		"RADIO_UPDATED": 3,
		"MUTED":         4,
		"UNMUTED":       5,
	}
)

func (x ClientDelta_Type) Enum() *ClientDelta_Type {
	p := new(ClientDelta_Type)
	*p = x
	return p
}

func (x ClientDelta_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientDelta_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_control_proto_enumTypes[2].Descriptor()
}

func (ClientDelta_Type) Type() protoreflect.EnumType {
	return &file_control_proto_enumTypes[2]
}

func (x ClientDelta_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientDelta_Type.Descriptor instead.
func (ClientDelta_Type) EnumDescriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{32, 0}
}

// Messages from Control Server to Voice Server
type ControlMessage struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ServerId string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	EventId  string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // Unique ID for this event
	// Types that are valid to be assigned to Command:
	//
	//	*ControlMessage_AssignFrequencies
	//	*ControlMessage_KickClient
	//	*ControlMessage_Shutdown
	//	*ControlMessage_Rebalance
	//	*ControlMessage_UpdateConfig
	//	*ControlMessage_StateSnapshot
	//	*ControlMessage_ClientDelta
	Command       isControlMessage_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *ControlMessage) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ControlMessage) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ControlMessage) GetCommand() isControlMessage_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ControlMessage) GetAssignFrequencies() *AssignFrequenciesRequest {
	if x != nil {
		if x, ok := x.Command.(*ControlMessage_AssignFrequencies); ok {
			return x.AssignFrequencies
		}
	}
	return nil
}

func (x *ControlMessage) GetKickClient() *KickClientRequest {
	if x != nil {
		if x, ok := x.Command.(*ControlMessage_KickClient); ok {
			return x.KickClient
		}
	}
	return nil
}

func (x *ControlMessage) GetShutdown() *ShutdownRequest {
	if x != nil {
		if x, ok := x.Command.(*ControlMessage_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

func (x *ControlMessage) GetRebalance() *RebalanceRequest {
	if x != nil {
		if x, ok := x.Command.(*ControlMessage_Rebalance); ok {
			return x.Rebalance
		}
	}
	return nil
}

func (x *ControlMessage) GetUpdateConfig() *UpdateConfigRequest {
	if x != nil {
		if x, ok := x.Command.(*ControlMessage_UpdateConfig); ok {
			return x.UpdateConfig
		}
	}
	return nil
}

func (x *ControlMessage) GetStateSnapshot() *ClientStateSnapshot {
	if x != nil {
		if x, ok := x.Command.(*ControlMessage_StateSnapshot); ok {
			return x.StateSnapshot
		}
	}
	return nil
}

func (x *ControlMessage) GetClientDelta() *ClientDelta {
	if x != nil {
		if x, ok := x.Command.(*ControlMessage_ClientDelta); ok {
			return x.ClientDelta
		}
	}
	return nil
}

type isControlMessage_Command interface {
	isControlMessage_Command()
}

type ControlMessage_AssignFrequencies struct {
	AssignFrequencies *AssignFrequenciesRequest `protobuf:"bytes,3,opt,name=assign_frequencies,json=assignFrequencies,proto3,oneof"`
}

type ControlMessage_KickClient struct {
	KickClient *KickClientRequest `protobuf:"bytes,4,opt,name=kick_client,json=kickClient,proto3,oneof"`
}

type ControlMessage_Shutdown struct {
	Shutdown *ShutdownRequest `protobuf:"bytes,5,opt,name=shutdown,proto3,oneof"`
}

type ControlMessage_Rebalance struct {
	Rebalance *RebalanceRequest `protobuf:"bytes,6,opt,name=rebalance,proto3,oneof"`
}

type ControlMessage_UpdateConfig struct {
	UpdateConfig *UpdateConfigRequest `protobuf:"bytes,7,opt,name=update_config,json=updateConfig,proto3,oneof"`
}

type ControlMessage_StateSnapshot struct {
	StateSnapshot *ClientStateSnapshot `protobuf:"bytes,8,opt,name=state_snapshot,json=stateSnapshot,proto3,oneof"`
}

type ControlMessage_ClientDelta struct {
	ClientDelta *ClientDelta `protobuf:"bytes,9,opt,name=client_delta,json=clientDelta,proto3,oneof"`
}

func (*ControlMessage_AssignFrequencies) isControlMessage_Command() {}

func (*ControlMessage_KickClient) isControlMessage_Command() {}

func (*ControlMessage_Shutdown) isControlMessage_Command() {}

func (*ControlMessage_Rebalance) isControlMessage_Command() {}

func (*ControlMessage_UpdateConfig) isControlMessage_Command() {}

func (*ControlMessage_StateSnapshot) isControlMessage_Command() {}

func (*ControlMessage_ClientDelta) isControlMessage_Command() {}

// Response for Control Messages
type ControlResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ServerId string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	EventId  string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // Matches the event_id from ControlMessage
	Success  bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message  string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*ControlResponse_AssignFrequenciesResponse
	//	*ControlResponse_KickClientResponse
	//	*ControlResponse_ShutdownResponse
	//	*ControlResponse_RebalanceResponse
	//	*ControlResponse_UpdateConfigResponse
	Result        isControlResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlResponse) Reset() {
	*x = ControlResponse{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlResponse) ProtoMessage() {}

func (x *ControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlResponse.ProtoReflect.Descriptor instead.
func (*ControlResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *ControlResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ControlResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ControlResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ControlResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ControlResponse) GetResult() isControlResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ControlResponse) GetAssignFrequenciesResponse() *AssignFrequenciesResponse {
	if x != nil {
		if x, ok := x.Result.(*ControlResponse_AssignFrequenciesResponse); ok {
			return x.AssignFrequenciesResponse
		}
	}
	return nil
}

func (x *ControlResponse) GetKickClientResponse() *KickClientResponse {
	if x != nil {
		if x, ok := x.Result.(*ControlResponse_KickClientResponse); ok {
			return x.KickClientResponse
		}
	}
	return nil
}

func (x *ControlResponse) GetShutdownResponse() *ShutdownResponse {
	if x != nil {
		if x, ok := x.Result.(*ControlResponse_ShutdownResponse); ok {
			return x.ShutdownResponse
		}
	}
	return nil
}

func (x *ControlResponse) GetRebalanceResponse() *RebalanceResponse {
	if x != nil {
		if x, ok := x.Result.(*ControlResponse_RebalanceResponse); ok {
			return x.RebalanceResponse
		}
	}
	return nil
}

func (x *ControlResponse) GetUpdateConfigResponse() *UpdateConfigResponse {
	if x != nil {
		if x, ok := x.Result.(*ControlResponse_UpdateConfigResponse); ok {
			return x.UpdateConfigResponse
		}
	}
	return nil
}

type isControlResponse_Result interface {
	isControlResponse_Result()
}

type ControlResponse_AssignFrequenciesResponse struct {
	AssignFrequenciesResponse *AssignFrequenciesResponse `protobuf:"bytes,5,opt,name=assign_frequencies_response,json=assignFrequenciesResponse,proto3,oneof"`
}

type ControlResponse_KickClientResponse struct {
	KickClientResponse *KickClientResponse `protobuf:"bytes,6,opt,name=kick_client_response,json=kickClientResponse,proto3,oneof"`
}

type ControlResponse_ShutdownResponse struct {
	ShutdownResponse *ShutdownResponse `protobuf:"bytes,7,opt,name=shutdown_response,json=shutdownResponse,proto3,oneof"`
}

type ControlResponse_RebalanceResponse struct {
	RebalanceResponse *RebalanceResponse `protobuf:"bytes,8,opt,name=rebalance_response,json=rebalanceResponse,proto3,oneof"`
}

type ControlResponse_UpdateConfigResponse struct {
	UpdateConfigResponse *UpdateConfigResponse `protobuf:"bytes,9,opt,name=update_config_response,json=updateConfigResponse,proto3,oneof"`
}

func (*ControlResponse_AssignFrequenciesResponse) isControlResponse_Result() {}

func (*ControlResponse_KickClientResponse) isControlResponse_Result() {}

func (*ControlResponse_ShutdownResponse) isControlResponse_Result() {}

func (*ControlResponse_RebalanceResponse) isControlResponse_Result() {}

func (*ControlResponse_UpdateConfigResponse) isControlResponse_Result() {}

// Configuration Updates
type UpdateConfigRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServerId         string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ConfigParameters map[string]string      `protobuf:"bytes,2,rep,name=config_parameters,json=configParameters,proto3" json:"config_parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Key-value pairs for config
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateConfigRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *UpdateConfigRequest) GetConfigParameters() map[string]string {
	if x != nil {
		return x.ConfigParameters
	}
	return nil
}

type UpdateConfigResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Success            bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message            string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AppliedParameters  map[string]string      `protobuf:"bytes,3,rep,name=applied_parameters,json=appliedParameters,proto3" json:"applied_parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Parameters that were successfully applied
	RejectedParameters []string               `protobuf:"bytes,4,rep,name=rejected_parameters,json=rejectedParameters,proto3" json:"rejected_parameters,omitempty"`                                                                        // Parameters that were rejected
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateConfigResponse) Reset() {
	*x = UpdateConfigResponse{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigResponse) ProtoMessage() {}

func (x *UpdateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateConfigResponse) GetAppliedParameters() map[string]string {
	if x != nil {
		return x.AppliedParameters
	}
	return nil
}

func (x *UpdateConfigResponse) GetRejectedParameters() []string {
	if x != nil {
		return x.RejectedParameters
	}
	return nil
}

// Voice Server Registration
type RegisterVoiceServerRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ServerId            string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServerAddress       string                 `protobuf:"bytes,2,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"`
	UdpPort             int32                  `protobuf:"varint,3,opt,name=udp_port,json=udpPort,proto3" json:"udp_port,omitempty"`
	IsGlobal            bool                   `protobuf:"varint,4,opt,name=is_global,json=isGlobal,proto3" json:"is_global,omitempty"` // true for the dedicated global freq node
	Capabilities        *ServerCapabilities    `protobuf:"bytes,5,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	Region              string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`                                                      // "eu" / "us" / "apac" (hint, not enforced)
	PreferredCoalitions []string               `protobuf:"bytes,7,rep,name=preferred_coalitions,json=preferredCoalitions,proto3" json:"preferred_coalitions,omitempty"` // empty = auto-assign
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterVoiceServerRequest) Reset() {
	*x = RegisterVoiceServerRequest{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterVoiceServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterVoiceServerRequest) ProtoMessage() {}

func (x *RegisterVoiceServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterVoiceServerRequest.ProtoReflect.Descriptor instead.
func (*RegisterVoiceServerRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterVoiceServerRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *RegisterVoiceServerRequest) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

func (x *RegisterVoiceServerRequest) GetUdpPort() int32 {
	if x != nil {
		return x.UdpPort
	}
	return 0
}

func (x *RegisterVoiceServerRequest) GetIsGlobal() bool {
	if x != nil {
		return x.IsGlobal
	}
	return false
}

func (x *RegisterVoiceServerRequest) GetCapabilities() *ServerCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterVoiceServerRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RegisterVoiceServerRequest) GetPreferredCoalitions() []string {
	if x != nil {
		return x.PreferredCoalitions
	}
	return nil
}

type RegisterVoiceServerResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Success             bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message             string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AssignedFrequencies []*FrequencyRange      `protobuf:"bytes,3,rep,name=assigned_frequencies,json=assignedFrequencies,proto3" json:"assigned_frequencies,omitempty"` // kept for freq-band overflow
	AssignedCoalitions  []string               `protobuf:"bytes,4,rep,name=assigned_coalitions,json=assignedCoalitions,proto3" json:"assigned_coalitions,omitempty"`    // NEW
	GlobalVoiceAddress  string                 `protobuf:"bytes,5,opt,name=global_voice_address,json=globalVoiceAddress,proto3" json:"global_voice_address,omitempty"`  // NEW — host:port of global node
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterVoiceServerResponse) Reset() {
	*x = RegisterVoiceServerResponse{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterVoiceServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterVoiceServerResponse) ProtoMessage() {}

func (x *RegisterVoiceServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterVoiceServerResponse.ProtoReflect.Descriptor instead.
func (*RegisterVoiceServerResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterVoiceServerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterVoiceServerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterVoiceServerResponse) GetAssignedFrequencies() []*FrequencyRange {
	if x != nil {
		return x.AssignedFrequencies
	}
	return nil
}

func (x *RegisterVoiceServerResponse) GetAssignedCoalitions() []string {
	if x != nil {
		return x.AssignedCoalitions
	}
	return nil
}

func (x *RegisterVoiceServerResponse) GetGlobalVoiceAddress() string {
	if x != nil {
		return x.GlobalVoiceAddress
	}
	return ""
}

type ServerCapabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"` // Version of the voice server
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCapabilities) Reset() {
	*x = ServerCapabilities{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCapabilities) ProtoMessage() {}

func (x *ServerCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCapabilities.ProtoReflect.Descriptor instead.
func (*ServerCapabilities) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

func (x *ServerCapabilities) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Heartbeat
type HeartbeatRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServerId         string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Status           *ServerStatus          `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ConnectedClients []*ClientInfo          `protobuf:"bytes,3,rep,name=connected_clients,json=connectedClients,proto3" json:"connected_clients,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() *ServerStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *HeartbeatRequest) GetConnectedClients() []*ClientInfo {
	if x != nil {
		return x.ConnectedClients
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	Commands      []*ControlCommand      `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetCommands() []*ControlCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

type ServerStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CpuUsagePercent    int32                  `protobuf:"varint,1,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemoryUsagePercent int32                  `protobuf:"varint,2,opt,name=memory_usage_percent,json=memoryUsagePercent,proto3" json:"memory_usage_percent,omitempty"`
	ActiveConnections  int32                  `protobuf:"varint,3,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	BytesSent          int64                  `protobuf:"varint,4,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesReceived      int64                  `protobuf:"varint,5,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	IsHealthy          bool                   `protobuf:"varint,6,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServerStatus) Reset() {
	*x = ServerStatus{}
	mi := &file_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatus) ProtoMessage() {}

func (x *ServerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatus.ProtoReflect.Descriptor instead.
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{9}
}

func (x *ServerStatus) GetCpuUsagePercent() int32 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *ServerStatus) GetMemoryUsagePercent() int32 {
	if x != nil {
		return x.MemoryUsagePercent
	}
	return 0
}

func (x *ServerStatus) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *ServerStatus) GetBytesSent() int64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *ServerStatus) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *ServerStatus) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

// Client Connection Events
type ClientConnectedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientAddress string                 `protobuf:"bytes,3,opt,name=client_address,json=clientAddress,proto3" json:"client_address,omitempty"`
	ClientPort    int32                  `protobuf:"varint,4,opt,name=client_port,json=clientPort,proto3" json:"client_port,omitempty"`
	Frequency     float64                `protobuf:"fixed64,5,opt,name=frequency,proto3" json:"frequency,omitempty"`
	ConnectedAt   int64                  `protobuf:"varint,6,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientConnectedRequest) Reset() {
	*x = ClientConnectedRequest{}
	mi := &file_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConnectedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConnectedRequest) ProtoMessage() {}

func (x *ClientConnectedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConnectedRequest.ProtoReflect.Descriptor instead.
func (*ClientConnectedRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{10}
}

func (x *ClientConnectedRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ClientConnectedRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientConnectedRequest) GetClientAddress() string {
	if x != nil {
		return x.ClientAddress
	}
	return ""
}

func (x *ClientConnectedRequest) GetClientPort() int32 {
	if x != nil {
		return x.ClientPort
	}
	return 0
}

func (x *ClientConnectedRequest) GetFrequency() float64 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *ClientConnectedRequest) GetConnectedAt() int64 {
	if x != nil {
		return x.ConnectedAt
	}
	return 0
}

type ClientConnectedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientConnectedResponse) Reset() {
	*x = ClientConnectedResponse{}
	mi := &file_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConnectedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConnectedResponse) ProtoMessage() {}

func (x *ClientConnectedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConnectedResponse.ProtoReflect.Descriptor instead.
func (*ClientConnectedResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{11}
}

func (x *ClientConnectedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClientConnectedResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ClientDisconnectedRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerId       string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ClientId       string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Reason         DisconnectReason       `protobuf:"varint,3,opt,name=reason,proto3,enum=voicecontrolpb.DisconnectReason" json:"reason,omitempty"`
	DisconnectedAt int64                  `protobuf:"varint,4,opt,name=disconnected_at,json=disconnectedAt,proto3" json:"disconnected_at,omitempty"` // Unix timestamp
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClientDisconnectedRequest) Reset() {
	*x = ClientDisconnectedRequest{}
	mi := &file_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDisconnectedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDisconnectedRequest) ProtoMessage() {}

func (x *ClientDisconnectedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDisconnectedRequest.ProtoReflect.Descriptor instead.
func (*ClientDisconnectedRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{12}
}

func (x *ClientDisconnectedRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ClientDisconnectedRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientDisconnectedRequest) GetReason() DisconnectReason {
	if x != nil {
		return x.Reason
	}
	return DisconnectReason_CLIENT_DISCONNECT
}

func (x *ClientDisconnectedRequest) GetDisconnectedAt() int64 {
	if x != nil {
		return x.DisconnectedAt
	}
	return 0
}

type ClientDisconnectedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientDisconnectedResponse) Reset() {
	*x = ClientDisconnectedResponse{}
	mi := &file_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDisconnectedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDisconnectedResponse) ProtoMessage() {}

func (x *ClientDisconnectedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDisconnectedResponse.ProtoReflect.Descriptor instead.
func (*ClientDisconnectedResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{13}
}

func (x *ClientDisconnectedResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

// Frequency Management
type FrequencyChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	OldFrequency  float64                `protobuf:"fixed64,3,opt,name=old_frequency,json=oldFrequency,proto3" json:"old_frequency,omitempty"`
	NewFrequency  float64                `protobuf:"fixed64,4,opt,name=new_frequency,json=newFrequency,proto3" json:"new_frequency,omitempty"`
	ChangedAt     int64                  `protobuf:"varint,5,opt,name=changed_at,json=changedAt,proto3" json:"changed_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrequencyChangeRequest) Reset() {
	*x = FrequencyChangeRequest{}
	mi := &file_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrequencyChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrequencyChangeRequest) ProtoMessage() {}

func (x *FrequencyChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrequencyChangeRequest.ProtoReflect.Descriptor instead.
func (*FrequencyChangeRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{14}
}

func (x *FrequencyChangeRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *FrequencyChangeRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *FrequencyChangeRequest) GetOldFrequency() float64 {
	if x != nil {
		return x.OldFrequency
	}
	return 0
}

func (x *FrequencyChangeRequest) GetNewFrequency() float64 {
	if x != nil {
		return x.NewFrequency
	}
	return 0
}

func (x *FrequencyChangeRequest) GetChangedAt() int64 {
	if x != nil {
		return x.ChangedAt
	}
	return 0
}

type FrequencyChangeResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Success              bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequiresServerChange bool                   `protobuf:"varint,3,opt,name=requires_server_change,json=requiresServerChange,proto3" json:"requires_server_change,omitempty"`
	NewServerId          string                 `protobuf:"bytes,4,opt,name=new_server_id,json=newServerId,proto3" json:"new_server_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FrequencyChangeResponse) Reset() {
	*x = FrequencyChangeResponse{}
	mi := &file_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrequencyChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrequencyChangeResponse) ProtoMessage() {}

func (x *FrequencyChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrequencyChangeResponse.ProtoReflect.Descriptor instead.
func (*FrequencyChangeResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{15}
}

func (x *FrequencyChangeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FrequencyChangeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FrequencyChangeResponse) GetRequiresServerChange() bool {
	if x != nil {
		return x.RequiresServerChange
	}
	return false
}

func (x *FrequencyChangeResponse) GetNewServerId() string {
	if x != nil {
		return x.NewServerId
	}
	return ""
}

type AssignFrequenciesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServerId        string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	FrequencyRanges []*FrequencyRange      `protobuf:"bytes,2,rep,name=frequency_ranges,json=frequencyRanges,proto3" json:"frequency_ranges,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AssignFrequenciesRequest) Reset() {
	*x = AssignFrequenciesRequest{}
	mi := &file_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignFrequenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignFrequenciesRequest) ProtoMessage() {}

func (x *AssignFrequenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignFrequenciesRequest.ProtoReflect.Descriptor instead.
func (*AssignFrequenciesRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{16}
}

func (x *AssignFrequenciesRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *AssignFrequenciesRequest) GetFrequencyRanges() []*FrequencyRange {
	if x != nil {
		return x.FrequencyRanges
	}
	return nil
}

type AssignFrequenciesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AcceptedRanges []*FrequencyRange      `protobuf:"bytes,3,rep,name=accepted_ranges,json=acceptedRanges,proto3" json:"accepted_ranges,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AssignFrequenciesResponse) Reset() {
	*x = AssignFrequenciesResponse{}
	mi := &file_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignFrequenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignFrequenciesResponse) ProtoMessage() {}

func (x *AssignFrequenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignFrequenciesResponse.ProtoReflect.Descriptor instead.
func (*AssignFrequenciesResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{17}
}

func (x *AssignFrequenciesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AssignFrequenciesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AssignFrequenciesResponse) GetAcceptedRanges() []*FrequencyRange {
	if x != nil {
		return x.AcceptedRanges
	}
	return nil
}

// TODO: Make this better with coalitions as well
type FrequencyRange struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StartFrequency float64                `protobuf:"fixed64,1,opt,name=start_frequency,json=startFrequency,proto3" json:"start_frequency,omitempty"`
	EndFrequency   float64                `protobuf:"fixed64,2,opt,name=end_frequency,json=endFrequency,proto3" json:"end_frequency,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FrequencyRange) Reset() {
	*x = FrequencyRange{}
	mi := &file_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrequencyRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrequencyRange) ProtoMessage() {}

func (x *FrequencyRange) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrequencyRange.ProtoReflect.Descriptor instead.
func (*FrequencyRange) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{18}
}

func (x *FrequencyRange) GetStartFrequency() float64 {
	if x != nil {
		return x.StartFrequency
	}
	return 0
}

func (x *FrequencyRange) GetEndFrequency() float64 {
	if x != nil {
		return x.EndFrequency
	}
	return 0
}

// Admin Actions
type KickClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	AdminId       string                 `protobuf:"bytes,4,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickClientRequest) Reset() {
	*x = KickClientRequest{}
	mi := &file_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickClientRequest) ProtoMessage() {}

func (x *KickClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickClientRequest.ProtoReflect.Descriptor instead.
func (*KickClientRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{19}
}

func (x *KickClientRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *KickClientRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *KickClientRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *KickClientRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

type KickClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickClientResponse) Reset() {
	*x = KickClientResponse{}
	mi := &file_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickClientResponse) ProtoMessage() {}

func (x *KickClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickClientResponse.ProtoReflect.Descriptor instead.
func (*KickClientResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{20}
}

func (x *KickClientResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *KickClientResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Server Management
type ShutdownRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerId       string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Graceful       bool                   `protobuf:"varint,2,opt,name=graceful,proto3" json:"graceful,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_control_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{21}
}

func (x *ShutdownRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ShutdownRequest) GetGraceful() bool {
	if x != nil {
		return x.Graceful
	}
	return false
}

func (x *ShutdownRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_control_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{22}
}

func (x *ShutdownResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *ShutdownResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RebalanceRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	ServerId      string                   `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Reassignments []*FrequencyReassignment `protobuf:"bytes,2,rep,name=reassignments,proto3" json:"reassignments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebalanceRequest) Reset() {
	*x = RebalanceRequest{}
	mi := &file_control_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebalanceRequest) ProtoMessage() {}

func (x *RebalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebalanceRequest.ProtoReflect.Descriptor instead.
func (*RebalanceRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{23}
}

func (x *RebalanceRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *RebalanceRequest) GetReassignments() []*FrequencyReassignment {
	if x != nil {
		return x.Reassignments
	}
	return nil
}

type RebalanceResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AffectedClients []string               `protobuf:"bytes,3,rep,name=affected_clients,json=affectedClients,proto3" json:"affected_clients,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RebalanceResponse) Reset() {
	*x = RebalanceResponse{}
	mi := &file_control_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebalanceResponse) ProtoMessage() {}

func (x *RebalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebalanceResponse.ProtoReflect.Descriptor instead.
func (*RebalanceResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{24}
}

func (x *RebalanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RebalanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RebalanceResponse) GetAffectedClients() []string {
	if x != nil {
		return x.AffectedClients
	}
	return nil
}

type FrequencyReassignment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Frequency       float64                `protobuf:"fixed64,1,opt,name=frequency,proto3" json:"frequency,omitempty"`
	FromServerId    string                 `protobuf:"bytes,2,opt,name=from_server_id,json=fromServerId,proto3" json:"from_server_id,omitempty"`
	ToServerId      string                 `protobuf:"bytes,3,opt,name=to_server_id,json=toServerId,proto3" json:"to_server_id,omitempty"`
	AffectedClients []string               `protobuf:"bytes,4,rep,name=affected_clients,json=affectedClients,proto3" json:"affected_clients,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FrequencyReassignment) Reset() {
	*x = FrequencyReassignment{}
	mi := &file_control_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrequencyReassignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrequencyReassignment) ProtoMessage() {}

func (x *FrequencyReassignment) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrequencyReassignment.ProtoReflect.Descriptor instead.
func (*FrequencyReassignment) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{25}
}

func (x *FrequencyReassignment) GetFrequency() float64 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *FrequencyReassignment) GetFromServerId() string {
	if x != nil {
		return x.FromServerId
	}
	return ""
}

func (x *FrequencyReassignment) GetToServerId() string {
	if x != nil {
		return x.ToServerId
	}
	return ""
}

func (x *FrequencyReassignment) GetAffectedClients() []string {
	if x != nil {
		return x.AffectedClients
	}
	return nil
}

// Common Data Types
type ClientInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientId       string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientAddress  string                 `protobuf:"bytes,2,opt,name=client_address,json=clientAddress,proto3" json:"client_address,omitempty"`
	ClientPort     int32                  `protobuf:"varint,3,opt,name=client_port,json=clientPort,proto3" json:"client_port,omitempty"`
	Frequency      float64                `protobuf:"fixed64,4,opt,name=frequency,proto3" json:"frequency,omitempty"`
	ConnectedAt    int64                  `protobuf:"varint,5,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	IsTransmitting bool                   `protobuf:"varint,6,opt,name=is_transmitting,json=isTransmitting,proto3" json:"is_transmitting,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	mi := &file_control_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{26}
}

func (x *ClientInfo) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientInfo) GetClientAddress() string {
	if x != nil {
		return x.ClientAddress
	}
	return ""
}

func (x *ClientInfo) GetClientPort() int32 {
	if x != nil {
		return x.ClientPort
	}
	return 0
}

func (x *ClientInfo) GetFrequency() float64 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *ClientInfo) GetConnectedAt() int64 {
	if x != nil {
		return x.ConnectedAt
	}
	return 0
}

func (x *ClientInfo) GetIsTransmitting() bool {
	if x != nil {
		return x.IsTransmitting
	}
	return false
}

type ControlCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           CommandType            `protobuf:"varint,1,opt,name=type,proto3,enum=voicecontrolpb.CommandType" json:"type,omitempty"`
	TargetClientId string                 `protobuf:"bytes,2,opt,name=target_client_id,json=targetClientId,proto3" json:"target_client_id,omitempty"`
	Parameters     map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ControlCommand) Reset() {
	*x = ControlCommand{}
	mi := &file_control_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlCommand) ProtoMessage() {}

func (x *ControlCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlCommand.ProtoReflect.Descriptor instead.
func (*ControlCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{27}
}

func (x *ControlCommand) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_NO_COMMAND
}

func (x *ControlCommand) GetTargetClientId() string {
	if x != nil {
		return x.TargetClientId
	}
	return ""
}

func (x *ControlCommand) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type ClientStateSnapshot struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Clients       map[string]*VoiceClientInfo `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Radios        map[string]*VoiceRadioInfo  `protobuf:"bytes,2,rep,name=radios,proto3" json:"radios,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientStateSnapshot) Reset() {
	*x = ClientStateSnapshot{}
	mi := &file_control_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientStateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStateSnapshot) ProtoMessage() {}

func (x *ClientStateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStateSnapshot.ProtoReflect.Descriptor instead.
func (*ClientStateSnapshot) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{28}
}

func (x *ClientStateSnapshot) GetClients() map[string]*VoiceClientInfo {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *ClientStateSnapshot) GetRadios() map[string]*VoiceRadioInfo {
	if x != nil {
		return x.Radios
	}
	return nil
}

type VoiceClientInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Coalition     string                 `protobuf:"bytes,2,opt,name=coalition,proto3" json:"coalition,omitempty"`
	UnitId        string                 `protobuf:"bytes,3,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	Role          uint32                 `protobuf:"varint,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceClientInfo) Reset() {
	*x = VoiceClientInfo{}
	mi := &file_control_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceClientInfo) ProtoMessage() {}

func (x *VoiceClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceClientInfo.ProtoReflect.Descriptor instead.
func (*VoiceClientInfo) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{29}
}

func (x *VoiceClientInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VoiceClientInfo) GetCoalition() string {
	if x != nil {
		return x.Coalition
	}
	return ""
}

func (x *VoiceClientInfo) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *VoiceClientInfo) GetRole() uint32 {
	if x != nil {
		return x.Role
	}
	return 0
}

type VoiceRadioInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Radios        []*VoiceRadio          `protobuf:"bytes,1,rep,name=radios,proto3" json:"radios,omitempty"`
	Muted         bool                   `protobuf:"varint,2,opt,name=muted,proto3" json:"muted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceRadioInfo) Reset() {
	*x = VoiceRadioInfo{}
	mi := &file_control_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceRadioInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceRadioInfo) ProtoMessage() {}

func (x *VoiceRadioInfo) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceRadioInfo.ProtoReflect.Descriptor instead.
func (*VoiceRadioInfo) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{30}
}

func (x *VoiceRadioInfo) GetRadios() []*VoiceRadio {
	if x != nil {
		return x.Radios
	}
	return nil
}

func (x *VoiceRadioInfo) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

type VoiceRadio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Frequency     float32                `protobuf:"fixed32,2,opt,name=frequency,proto3" json:"frequency,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	IsIntercom    bool                   `protobuf:"varint,4,opt,name=is_intercom,json=isIntercom,proto3" json:"is_intercom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceRadio) Reset() {
	*x = VoiceRadio{}
	mi := &file_control_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceRadio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceRadio) ProtoMessage() {}

func (x *VoiceRadio) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceRadio.ProtoReflect.Descriptor instead.
func (*VoiceRadio) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{31}
}

func (x *VoiceRadio) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VoiceRadio) GetFrequency() float32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *VoiceRadio) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *VoiceRadio) GetIsIntercom() bool {
	if x != nil {
		return x.IsIntercom
	}
	return false
}

type ClientDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ClientDelta_Type       `protobuf:"varint,1,opt,name=type,proto3,enum=voicecontrolpb.ClientDelta_Type" json:"type,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientInfo    *VoiceClientInfo       `protobuf:"bytes,3,opt,name=client_info,json=clientInfo,proto3" json:"client_info,omitempty"` // populated for JOINED, INFO_UPDATED
	RadioInfo     *VoiceRadioInfo        `protobuf:"bytes,4,opt,name=radio_info,json=radioInfo,proto3" json:"radio_info,omitempty"`    // populated for RADIO_UPDATED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientDelta) Reset() {
	*x = ClientDelta{}
	mi := &file_control_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDelta) ProtoMessage() {}

func (x *ClientDelta) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDelta.ProtoReflect.Descriptor instead.
func (*ClientDelta) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{32}
}

func (x *ClientDelta) GetType() ClientDelta_Type {
	if x != nil {
		return x.Type
	}
	return ClientDelta_JOINED
}

func (x *ClientDelta) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientDelta) GetClientInfo() *VoiceClientInfo {
	if x != nil {
		return x.ClientInfo
	}
	return nil
}

func (x *ClientDelta) GetRadioInfo() *VoiceRadioInfo {
	if x != nil {
		return x.RadioInfo
	}
	return nil
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\x0evoicecontrolpb\"\xd1\x04\n" +
	"\x0eControlMessage\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12Y\n" +
	"\x12assign_frequencies\x18\x03 \x01(\v2(.voicecontrolpb.AssignFrequenciesRequestH\x00R\x11assignFrequencies\x12D\n" +
	"\vkick_client\x18\x04 \x01(\v2!.voicecontrolpb.KickClientRequestH\x00R\n" +
	"kickClient\x12=\n" +
	"\bshutdown\x18\x05 \x01(\v2\x1f.voicecontrolpb.ShutdownRequestH\x00R\bshutdown\x12@\n" +
	"\trebalance\x18\x06 \x01(\v2 .voicecontrolpb.RebalanceRequestH\x00R\trebalance\x12J\n" +
	"\rupdate_config\x18\a \x01(\v2#.voicecontrolpb.UpdateConfigRequestH\x00R\fupdateConfig\x12L\n" +
	"\x0estate_snapshot\x18\b \x01(\v2#.voicecontrolpb.ClientStateSnapshotH\x00R\rstateSnapshot\x12@\n" +
	"\fclient_delta\x18\t \x01(\v2\x1b.voicecontrolpb.ClientDeltaH\x00R\vclientDeltaB\t\n" +
	"\acommand\"\xcf\x04\n" +
	"\x0fControlResponse\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12k\n" +
	"\x1bassign_frequencies_response\x18\x05 \x01(\v2).voicecontrolpb.AssignFrequenciesResponseH\x00R\x19assignFrequenciesResponse\x12V\n" +
	"\x14kick_client_response\x18\x06 \x01(\v2\".voicecontrolpb.KickClientResponseH\x00R\x12kickClientResponse\x12O\n" +
	"\x11shutdown_response\x18\a \x01(\v2 .voicecontrolpb.ShutdownResponseH\x00R\x10shutdownResponse\x12R\n" +
	"\x12rebalance_response\x18\b \x01(\v2!.voicecontrolpb.RebalanceResponseH\x00R\x11rebalanceResponse\x12\\\n" +
	"\x16update_config_response\x18\t \x01(\v2$.voicecontrolpb.UpdateConfigResponseH\x00R\x14updateConfigResponseB\b\n" +
	"\x06result\"\xdf\x01\n" +
	"\x13UpdateConfigRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12f\n" +
	"\x11config_parameters\x18\x02 \x03(\v29.voicecontrolpb.UpdateConfigRequest.ConfigParametersEntryR\x10configParameters\x1aC\n" +
	"\x15ConfigParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xad\x02\n" +
	"\x14UpdateConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12j\n" +
	"\x12applied_parameters\x18\x03 \x03(\v2;.voicecontrolpb.UpdateConfigResponse.AppliedParametersEntryR\x11appliedParameters\x12/\n" +
	"\x13rejected_parameters\x18\x04 \x03(\tR\x12rejectedParameters\x1aD\n" +
	"\x16AppliedParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xab\x02\n" +
	"\x1aRegisterVoiceServerRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12%\n" +
	"\x0eserver_address\x18\x02 \x01(\tR\rserverAddress\x12\x19\n" +
	"\budp_port\x18\x03 \x01(\x05R\audpPort\x12\x1b\n" +
	"\tis_global\x18\x04 \x01(\bR\bisGlobal\x12F\n" +
	"\fcapabilities\x18\x05 \x01(\v2\".voicecontrolpb.ServerCapabilitiesR\fcapabilities\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\x121\n" +
	"\x14preferred_coalitions\x18\a \x03(\tR\x13preferredCoalitions\"\x87\x02\n" +
	"\x1bRegisterVoiceServerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12Q\n" +
	"\x14assigned_frequencies\x18\x03 \x03(\v2\x1e.voicecontrolpb.FrequencyRangeR\x13assignedFrequencies\x12/\n" +
	"\x13assigned_coalitions\x18\x04 \x03(\tR\x12assignedCoalitions\x120\n" +
	"\x14global_voice_address\x18\x05 \x01(\tR\x12globalVoiceAddress\".\n" +
	"\x12ServerCapabilities\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\xae\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x124\n" +
	"\x06status\x18\x02 \x01(\v2\x1c.voicecontrolpb.ServerStatusR\x06status\x12G\n" +
	"\x11connected_clients\x18\x03 \x03(\v2\x1a.voicecontrolpb.ClientInfoR\x10connectedClients\"s\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12:\n" +
	"\bcommands\x18\x02 \x03(\v2\x1e.voicecontrolpb.ControlCommandR\bcommands\"\x80\x02\n" +
	"\fServerStatus\x12*\n" +
	"\x11cpu_usage_percent\x18\x01 \x01(\x05R\x0fcpuUsagePercent\x120\n" +
	"\x14memory_usage_percent\x18\x02 \x01(\x05R\x12memoryUsagePercent\x12-\n" +
	"\x12active_connections\x18\x03 \x01(\x05R\x11activeConnections\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x04 \x01(\x03R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\x05 \x01(\x03R\rbytesReceived\x12\x1d\n" +
	"\n" +
	"is_healthy\x18\x06 \x01(\bR\tisHealthy\"\xdb\x01\n" +
	"\x16ClientConnectedRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12%\n" +
	"\x0eclient_address\x18\x03 \x01(\tR\rclientAddress\x12\x1f\n" +
	"\vclient_port\x18\x04 \x01(\x05R\n" +
	"clientPort\x12\x1c\n" +
	"\tfrequency\x18\x05 \x01(\x01R\tfrequency\x12!\n" +
	"\fconnected_at\x18\x06 \x01(\x03R\vconnectedAt\"M\n" +
	"\x17ClientConnectedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb8\x01\n" +
	"\x19ClientDisconnectedRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x128\n" +
	"\x06reason\x18\x03 \x01(\x0e2 .voicecontrolpb.DisconnectReasonR\x06reason\x12'\n" +
	"\x0fdisconnected_at\x18\x04 \x01(\x03R\x0edisconnectedAt\"@\n" +
	"\x1aClientDisconnectedResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"\xbb\x01\n" +
	"\x16FrequencyChangeRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12#\n" +
	"\rold_frequency\x18\x03 \x01(\x01R\foldFrequency\x12#\n" +
	"\rnew_frequency\x18\x04 \x01(\x01R\fnewFrequency\x12\x1d\n" +
	"\n" +
	"changed_at\x18\x05 \x01(\x03R\tchangedAt\"\xa7\x01\n" +
	"\x17FrequencyChangeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\x16requires_server_change\x18\x03 \x01(\bR\x14requiresServerChange\x12\"\n" +
	"\rnew_server_id\x18\x04 \x01(\tR\vnewServerId\"\x82\x01\n" +
	"\x18AssignFrequenciesRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12I\n" +
	"\x10frequency_ranges\x18\x02 \x03(\v2\x1e.voicecontrolpb.FrequencyRangeR\x0ffrequencyRanges\"\x98\x01\n" +
	"\x19AssignFrequenciesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12G\n" +
	"\x0faccepted_ranges\x18\x03 \x03(\v2\x1e.voicecontrolpb.FrequencyRangeR\x0eacceptedRanges\"^\n" +
	"\x0eFrequencyRange\x12'\n" +
	"\x0fstart_frequency\x18\x01 \x01(\x01R\x0estartFrequency\x12#\n" +
	"\rend_frequency\x18\x02 \x01(\x01R\fendFrequency\"\x80\x01\n" +
	"\x11KickClientRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x19\n" +
	"\badmin_id\x18\x04 \x01(\tR\aadminId\"H\n" +
	"\x12KickClientResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"s\n" +
	"\x0fShutdownRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1a\n" +
	"\bgraceful\x18\x02 \x01(\bR\bgraceful\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\"P\n" +
	"\x10ShutdownResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"|\n" +
	"\x10RebalanceRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12K\n" +
	"\rreassignments\x18\x02 \x03(\v2%.voicecontrolpb.FrequencyReassignmentR\rreassignments\"r\n" +
	"\x11RebalanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x10affected_clients\x18\x03 \x03(\tR\x0faffectedClients\"\xa8\x01\n" +
	"\x15FrequencyReassignment\x12\x1c\n" +
	"\tfrequency\x18\x01 \x01(\x01R\tfrequency\x12$\n" +
	"\x0efrom_server_id\x18\x02 \x01(\tR\ffromServerId\x12 \n" +
	"\fto_server_id\x18\x03 \x01(\tR\n" +
	"toServerId\x12)\n" +
	"\x10affected_clients\x18\x04 \x03(\tR\x0faffectedClients\"\xdb\x01\n" +
	"\n" +
	"ClientInfo\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12%\n" +
	"\x0eclient_address\x18\x02 \x01(\tR\rclientAddress\x12\x1f\n" +
	"\vclient_port\x18\x03 \x01(\x05R\n" +
	"clientPort\x12\x1c\n" +
	"\tfrequency\x18\x04 \x01(\x01R\tfrequency\x12!\n" +
	"\fconnected_at\x18\x05 \x01(\x03R\vconnectedAt\x12'\n" +
	"\x0fis_transmitting\x18\x06 \x01(\bR\x0eisTransmitting\"\xfa\x01\n" +
	"\x0eControlCommand\x12/\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1b.voicecontrolpb.CommandTypeR\x04type\x12(\n" +
	"\x10target_client_id\x18\x02 \x01(\tR\x0etargetClientId\x12N\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2..voicecontrolpb.ControlCommand.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe2\x02\n" +
	"\x13ClientStateSnapshot\x12J\n" +
	"\aclients\x18\x01 \x03(\v20.voicecontrolpb.ClientStateSnapshot.ClientsEntryR\aclients\x12G\n" +
	"\x06radios\x18\x02 \x03(\v2/.voicecontrolpb.ClientStateSnapshot.RadiosEntryR\x06radios\x1a[\n" +
	"\fClientsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.voicecontrolpb.VoiceClientInfoR\x05value:\x028\x01\x1aY\n" +
	"\vRadiosEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.voicecontrolpb.VoiceRadioInfoR\x05value:\x028\x01\"p\n" +
	"\x0fVoiceClientInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tcoalition\x18\x02 \x01(\tR\tcoalition\x12\x17\n" +
	"\aunit_id\x18\x03 \x01(\tR\x06unitId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\rR\x04role\"Z\n" +
	"\x0eVoiceRadioInfo\x122\n" +
	"\x06radios\x18\x01 \x03(\v2\x1a.voicecontrolpb.VoiceRadioR\x06radios\x12\x14\n" +
	"\x05muted\x18\x02 \x01(\bR\x05muted\"u\n" +
	"\n" +
	"VoiceRadio\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1c\n" +
	"\tfrequency\x18\x02 \x01(\x02R\tfrequency\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12\x1f\n" +
	"\vis_intercom\x18\x04 \x01(\bR\n" +
	"isIntercom\"\xbc\x02\n" +
	"\vClientDelta\x124\n" +
	"\x04type\x18\x01 \x01(\x0e2 .voicecontrolpb.ClientDelta.TypeR\x04type\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12@\n" +
	"\vclient_info\x18\x03 \x01(\v2\x1f.voicecontrolpb.VoiceClientInfoR\n" +
	"clientInfo\x12=\n" +
	"\n" +
	"radio_info\x18\x04 \x01(\v2\x1e.voicecontrolpb.VoiceRadioInfoR\tradioInfo\"Y\n" +
	"\x04Type\x12\n" +
	"\n" +
	"\x06JOINED\x10\x00\x12\b\n" +
	"\x04LEFT\x10\x01\x12\x10\n" +
	"\fINFO_UPDATED\x10\x02\x12\x11\n" +
	"\rRADIO_UPDATED\x10\x03\x12\t\n" +
	"\x05MUTED\x10\x04\x12\v\n" +
	"\aUNMUTED\x10\x05*s\n" +
	"\x10DisconnectReason\x12\x15\n" +
	"\x11CLIENT_DISCONNECT\x10\x00\x12\n" +
	"\n" +
	"\x06KICKED\x10\x01\x12\v\n" +
	"\aTIMEOUT\x10\x02\x12\x13\n" +
	"\x0fSERVER_SHUTDOWN\x10\x03\x12\x1a\n" +
	"\x16FREQUENCY_REASSIGNMENT\x10\x04*e\n" +
	"\vCommandType\x12\x0e\n" +
	"\n" +
	"NO_COMMAND\x10\x00\x12\x0f\n" +
	"\vKICK_CLIENT\x10\x01\x12\x14\n" +
	"\x10CHANGE_FREQUENCY\x10\x02\x12\x11\n" +
	"\rUPDATE_CONFIG\x10\x03\x12\f\n" +
	"\bSHUTDOWN\x10\x042\xfa\x04\n" +
	"\x13VoiceControlService\x12n\n" +
	"\x13RegisterVoiceServer\x12*.voicecontrolpb.RegisterVoiceServerRequest\x1a+.voicecontrolpb.RegisterVoiceServerResponse\x12T\n" +
	"\rSendHeartbeat\x12 .voicecontrolpb.HeartbeatRequest\x1a!.voicecontrolpb.HeartbeatResponse\x12h\n" +
	"\x15ReportClientConnected\x12&.voicecontrolpb.ClientConnectedRequest\x1a'.voicecontrolpb.ClientConnectedResponse\x12q\n" +
	"\x18ReportClientDisconnected\x12).voicecontrolpb.ClientDisconnectedRequest\x1a*.voicecontrolpb.ClientDisconnectedResponse\x12h\n" +
	"\x15ReportFrequencyChange\x12&.voicecontrolpb.FrequencyChangeRequest\x1a'.voicecontrolpb.FrequencyChangeResponse\x12V\n" +
	"\x0fEstablishStream\x12\x1f.voicecontrolpb.ControlResponse\x1a\x1e.voicecontrolpb.ControlMessage(\x010\x01B4Z2github.com/FPGSchiba/vcs-srs-server/voicecontrolpbb\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_control_proto_goTypes = []any{
	(DisconnectReason)(0),               // 0: voicecontrolpb.DisconnectReason
	(CommandType)(0),                    // 1: voicecontrolpb.CommandType
	(ClientDelta_Type)(0),               // 2: voicecontrolpb.ClientDelta.Type
	(*ControlMessage)(nil),              // 3: voicecontrolpb.ControlMessage
	(*ControlResponse)(nil),             // 4: voicecontrolpb.ControlResponse
	(*UpdateConfigRequest)(nil),         // 5: voicecontrolpb.UpdateConfigRequest
	(*UpdateConfigResponse)(nil),        // 6: voicecontrolpb.UpdateConfigResponse
	(*RegisterVoiceServerRequest)(nil),  // 7: voicecontrolpb.RegisterVoiceServerRequest
	(*RegisterVoiceServerResponse)(nil), // 8: voicecontrolpb.RegisterVoiceServerResponse
	(*ServerCapabilities)(nil),          // 9: voicecontrolpb.ServerCapabilities
	(*HeartbeatRequest)(nil),            // 10: voicecontrolpb.HeartbeatRequest
	(*HeartbeatResponse)(nil),           // 11: voicecontrolpb.HeartbeatResponse
	(*ServerStatus)(nil),                // 12: voicecontrolpb.ServerStatus
	(*ClientConnectedRequest)(nil),      // 13: voicecontrolpb.ClientConnectedRequest
	(*ClientConnectedResponse)(nil),     // 14: voicecontrolpb.ClientConnectedResponse
	(*ClientDisconnectedRequest)(nil),   // 15: voicecontrolpb.ClientDisconnectedRequest
	(*ClientDisconnectedResponse)(nil),  // 16: voicecontrolpb.ClientDisconnectedResponse
	(*FrequencyChangeRequest)(nil),      // 17: voicecontrolpb.FrequencyChangeRequest
	(*FrequencyChangeResponse)(nil),     // 18: voicecontrolpb.FrequencyChangeResponse
	(*AssignFrequenciesRequest)(nil),    // 19: voicecontrolpb.AssignFrequenciesRequest
	(*AssignFrequenciesResponse)(nil),   // 20: voicecontrolpb.AssignFrequenciesResponse
	(*FrequencyRange)(nil),              // 21: voicecontrolpb.FrequencyRange
	(*KickClientRequest)(nil),           // 22: voicecontrolpb.KickClientRequest
	(*KickClientResponse)(nil),          // 23: voicecontrolpb.KickClientResponse
	(*ShutdownRequest)(nil),             // 24: voicecontrolpb.ShutdownRequest
	(*ShutdownResponse)(nil),            // 25: voicecontrolpb.ShutdownResponse
	(*RebalanceRequest)(nil),            // 26: voicecontrolpb.RebalanceRequest
	(*RebalanceResponse)(nil),           // 27: voicecontrolpb.RebalanceResponse
	(*FrequencyReassignment)(nil),       // 28: voicecontrolpb.FrequencyReassignment
	(*ClientInfo)(nil),                  // 29: voicecontrolpb.ClientInfo
	(*ControlCommand)(nil),              // 30: voicecontrolpb.ControlCommand
	(*ClientStateSnapshot)(nil),         // 31: voicecontrolpb.ClientStateSnapshot
	(*VoiceClientInfo)(nil),             // 32: voicecontrolpb.VoiceClientInfo
	(*VoiceRadioInfo)(nil),              // 33: voicecontrolpb.VoiceRadioInfo
	(*VoiceRadio)(nil),                  // 34: voicecontrolpb.VoiceRadio
	(*ClientDelta)(nil),                 // 35: voicecontrolpb.ClientDelta
	nil,                                 // 36: voicecontrolpb.UpdateConfigRequest.ConfigParametersEntry
	nil,                                 // 37: voicecontrolpb.UpdateConfigResponse.AppliedParametersEntry
	nil,                                 // 38: voicecontrolpb.ControlCommand.ParametersEntry
	nil,                                 // 39: voicecontrolpb.ClientStateSnapshot.ClientsEntry
	nil,                                 // 40: voicecontrolpb.ClientStateSnapshot.RadiosEntry
}
var file_control_proto_depIdxs = []int32{
	19, // 0: voicecontrolpb.ControlMessage.assign_frequencies:type_name -> voicecontrolpb.AssignFrequenciesRequest
	22, // 1: voicecontrolpb.ControlMessage.kick_client:type_name -> voicecontrolpb.KickClientRequest
	24, // 2: voicecontrolpb.ControlMessage.shutdown:type_name -> voicecontrolpb.ShutdownRequest
	26, // 3: voicecontrolpb.ControlMessage.rebalance:type_name -> voicecontrolpb.RebalanceRequest
	5,  // 4: voicecontrolpb.ControlMessage.update_config:type_name -> voicecontrolpb.UpdateConfigRequest
	31, // 5: voicecontrolpb.ControlMessage.state_snapshot:type_name -> voicecontrolpb.ClientStateSnapshot
	35, // 6: voicecontrolpb.ControlMessage.client_delta:type_name -> voicecontrolpb.ClientDelta
	20, // 7: voicecontrolpb.ControlResponse.assign_frequencies_response:type_name -> voicecontrolpb.AssignFrequenciesResponse
	23, // 8: voicecontrolpb.ControlResponse.kick_client_response:type_name -> voicecontrolpb.KickClientResponse
	25, // 9: voicecontrolpb.ControlResponse.shutdown_response:type_name -> voicecontrolpb.ShutdownResponse
	27, // 10: voicecontrolpb.ControlResponse.rebalance_response:type_name -> voicecontrolpb.RebalanceResponse
	6,  // 11: voicecontrolpb.ControlResponse.update_config_response:type_name -> voicecontrolpb.UpdateConfigResponse
	36, // 12: voicecontrolpb.UpdateConfigRequest.config_parameters:type_name -> voicecontrolpb.UpdateConfigRequest.ConfigParametersEntry
	37, // 13: voicecontrolpb.UpdateConfigResponse.applied_parameters:type_name -> voicecontrolpb.UpdateConfigResponse.AppliedParametersEntry
	9,  // 14: voicecontrolpb.RegisterVoiceServerRequest.capabilities:type_name -> voicecontrolpb.ServerCapabilities
	21, // 15: voicecontrolpb.RegisterVoiceServerResponse.assigned_frequencies:type_name -> voicecontrolpb.FrequencyRange
	12, // 16: voicecontrolpb.HeartbeatRequest.status:type_name -> voicecontrolpb.ServerStatus
	29, // 17: voicecontrolpb.HeartbeatRequest.connected_clients:type_name -> voicecontrolpb.ClientInfo
	30, // 18: voicecontrolpb.HeartbeatResponse.commands:type_name -> voicecontrolpb.ControlCommand
	0,  // 19: voicecontrolpb.ClientDisconnectedRequest.reason:type_name -> voicecontrolpb.DisconnectReason
	21, // 20: voicecontrolpb.AssignFrequenciesRequest.frequency_ranges:type_name -> voicecontrolpb.FrequencyRange
	21, // 21: voicecontrolpb.AssignFrequenciesResponse.accepted_ranges:type_name -> voicecontrolpb.FrequencyRange
	28, // 22: voicecontrolpb.RebalanceRequest.reassignments:type_name -> voicecontrolpb.FrequencyReassignment
	1,  // 23: voicecontrolpb.ControlCommand.type:type_name -> voicecontrolpb.CommandType
	38, // 24: voicecontrolpb.ControlCommand.parameters:type_name -> voicecontrolpb.ControlCommand.ParametersEntry
	39, // 25: voicecontrolpb.ClientStateSnapshot.clients:type_name -> voicecontrolpb.ClientStateSnapshot.ClientsEntry
	40, // 26: voicecontrolpb.ClientStateSnapshot.radios:type_name -> voicecontrolpb.ClientStateSnapshot.RadiosEntry
	34, // 27: voicecontrolpb.VoiceRadioInfo.radios:type_name -> voicecontrolpb.VoiceRadio
	2,  // 28: voicecontrolpb.ClientDelta.type:type_name -> voicecontrolpb.ClientDelta.Type
	32, // 29: voicecontrolpb.ClientDelta.client_info:type_name -> voicecontrolpb.VoiceClientInfo
	33, // 30: voicecontrolpb.ClientDelta.radio_info:type_name -> voicecontrolpb.VoiceRadioInfo
	32, // 31: voicecontrolpb.ClientStateSnapshot.ClientsEntry.value:type_name -> voicecontrolpb.VoiceClientInfo
	33, // 32: voicecontrolpb.ClientStateSnapshot.RadiosEntry.value:type_name -> voicecontrolpb.VoiceRadioInfo
	7,  // 33: voicecontrolpb.VoiceControlService.RegisterVoiceServer:input_type -> voicecontrolpb.RegisterVoiceServerRequest
	10, // 34: voicecontrolpb.VoiceControlService.SendHeartbeat:input_type -> voicecontrolpb.HeartbeatRequest
	13, // 35: voicecontrolpb.VoiceControlService.ReportClientConnected:input_type -> voicecontrolpb.ClientConnectedRequest
	15, // 36: voicecontrolpb.VoiceControlService.ReportClientDisconnected:input_type -> voicecontrolpb.ClientDisconnectedRequest
	17, // 37: voicecontrolpb.VoiceControlService.ReportFrequencyChange:input_type -> voicecontrolpb.FrequencyChangeRequest
	4,  // 38: voicecontrolpb.VoiceControlService.EstablishStream:input_type -> voicecontrolpb.ControlResponse
	8,  // 39: voicecontrolpb.VoiceControlService.RegisterVoiceServer:output_type -> voicecontrolpb.RegisterVoiceServerResponse
	11, // 40: voicecontrolpb.VoiceControlService.SendHeartbeat:output_type -> voicecontrolpb.HeartbeatResponse
	14, // 41: voicecontrolpb.VoiceControlService.ReportClientConnected:output_type -> voicecontrolpb.ClientConnectedResponse
	16, // 42: voicecontrolpb.VoiceControlService.ReportClientDisconnected:output_type -> voicecontrolpb.ClientDisconnectedResponse
	18, // 43: voicecontrolpb.VoiceControlService.ReportFrequencyChange:output_type -> voicecontrolpb.FrequencyChangeResponse
	3,  // 44: voicecontrolpb.VoiceControlService.EstablishStream:output_type -> voicecontrolpb.ControlMessage
	39, // [39:45] is the sub-list for method output_type
	33, // [33:39] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	file_control_proto_msgTypes[0].OneofWrappers = []any{
		(*ControlMessage_AssignFrequencies)(nil),
		(*ControlMessage_KickClient)(nil),
		(*ControlMessage_Shutdown)(nil),
		(*ControlMessage_Rebalance)(nil),
		(*ControlMessage_UpdateConfig)(nil),
		(*ControlMessage_StateSnapshot)(nil),
		(*ControlMessage_ClientDelta)(nil),
	}
	file_control_proto_msgTypes[1].OneofWrappers = []any{
		(*ControlResponse_AssignFrequenciesResponse)(nil),
		(*ControlResponse_KickClientResponse)(nil),
		(*ControlResponse_ShutdownResponse)(nil),
		(*ControlResponse_RebalanceResponse)(nil),
		(*ControlResponse_UpdateConfigResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		EnumInfos:         file_control_proto_enumTypes,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
