// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.30.2
// source: srs.proto

package srspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_InitAuth_FullMethodName                    = "/srspb.AuthService/InitAuth"
	AuthService_DiscoverAuthenticationFlows_FullMethodName = "/srspb.AuthService/DiscoverAuthenticationFlows"
	AuthService_GuestLogin_FullMethodName                  = "/srspb.AuthService/GuestLogin"
	AuthService_StartAuth_FullMethodName                   = "/srspb.AuthService/StartAuth"
	AuthService_ContinueAuth_FullMethodName                = "/srspb.AuthService/ContinueAuth"
	AuthService_UnitSelect_FullMethodName                  = "/srspb.AuthService/UnitSelect"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	// Get Available Plugins
	InitAuth(ctx context.Context, in *AuthInitRequest, opts ...grpc.CallOption) (*AuthInitResponse, error)
	// Discover available authentication flows for a specific plugin
	DiscoverAuthenticationFlows(ctx context.Context, in *FlowDiscoveryRequest, opts ...grpc.CallOption) (*FlowDiscoveryResponse, error)
	// Guest login (coalition password + user chosen name)
	GuestLogin(ctx context.Context, in *GuestLoginRequest, opts ...grpc.CallOption) (*GuestLoginResponse, error)
	// Plugin-based authentication (multi-step support)
	StartAuth(ctx context.Context, in *StartAuthRequest, opts ...grpc.CallOption) (*AuthStepResponse, error)
	ContinueAuth(ctx context.Context, in *ContinueAuthRequest, opts ...grpc.CallOption) (*AuthStepResponse, error)
	// Vanguard unit selection (after successful login)
	UnitSelect(ctx context.Context, in *UnitSelectRequest, opts ...grpc.CallOption) (*UnitSelectResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) InitAuth(ctx context.Context, in *AuthInitRequest, opts ...grpc.CallOption) (*AuthInitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthInitResponse)
	err := c.cc.Invoke(ctx, AuthService_InitAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) DiscoverAuthenticationFlows(ctx context.Context, in *FlowDiscoveryRequest, opts ...grpc.CallOption) (*FlowDiscoveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlowDiscoveryResponse)
	err := c.cc.Invoke(ctx, AuthService_DiscoverAuthenticationFlows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GuestLogin(ctx context.Context, in *GuestLoginRequest, opts ...grpc.CallOption) (*GuestLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GuestLoginResponse)
	err := c.cc.Invoke(ctx, AuthService_GuestLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) StartAuth(ctx context.Context, in *StartAuthRequest, opts ...grpc.CallOption) (*AuthStepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthStepResponse)
	err := c.cc.Invoke(ctx, AuthService_StartAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ContinueAuth(ctx context.Context, in *ContinueAuthRequest, opts ...grpc.CallOption) (*AuthStepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthStepResponse)
	err := c.cc.Invoke(ctx, AuthService_ContinueAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) UnitSelect(ctx context.Context, in *UnitSelectRequest, opts ...grpc.CallOption) (*UnitSelectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnitSelectResponse)
	err := c.cc.Invoke(ctx, AuthService_UnitSelect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
type AuthServiceServer interface {
	// Get Available Plugins
	InitAuth(context.Context, *AuthInitRequest) (*AuthInitResponse, error)
	// Discover available authentication flows for a specific plugin
	DiscoverAuthenticationFlows(context.Context, *FlowDiscoveryRequest) (*FlowDiscoveryResponse, error)
	// Guest login (coalition password + user chosen name)
	GuestLogin(context.Context, *GuestLoginRequest) (*GuestLoginResponse, error)
	// Plugin-based authentication (multi-step support)
	StartAuth(context.Context, *StartAuthRequest) (*AuthStepResponse, error)
	ContinueAuth(context.Context, *ContinueAuthRequest) (*AuthStepResponse, error)
	// Vanguard unit selection (after successful login)
	UnitSelect(context.Context, *UnitSelectRequest) (*UnitSelectResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) InitAuth(context.Context, *AuthInitRequest) (*AuthInitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitAuth not implemented")
}
func (UnimplementedAuthServiceServer) DiscoverAuthenticationFlows(context.Context, *FlowDiscoveryRequest) (*FlowDiscoveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiscoverAuthenticationFlows not implemented")
}
func (UnimplementedAuthServiceServer) GuestLogin(context.Context, *GuestLoginRequest) (*GuestLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GuestLogin not implemented")
}
func (UnimplementedAuthServiceServer) StartAuth(context.Context, *StartAuthRequest) (*AuthStepResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartAuth not implemented")
}
func (UnimplementedAuthServiceServer) ContinueAuth(context.Context, *ContinueAuthRequest) (*AuthStepResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ContinueAuth not implemented")
}
func (UnimplementedAuthServiceServer) UnitSelect(context.Context, *UnitSelectRequest) (*UnitSelectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnitSelect not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_InitAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthInitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).InitAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_InitAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).InitAuth(ctx, req.(*AuthInitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_DiscoverAuthenticationFlows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlowDiscoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).DiscoverAuthenticationFlows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_DiscoverAuthenticationFlows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).DiscoverAuthenticationFlows(ctx, req.(*FlowDiscoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GuestLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuestLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GuestLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GuestLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GuestLogin(ctx, req.(*GuestLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_StartAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).StartAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_StartAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).StartAuth(ctx, req.(*StartAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ContinueAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContinueAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ContinueAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ContinueAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ContinueAuth(ctx, req.(*ContinueAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_UnitSelect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnitSelectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UnitSelect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_UnitSelect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UnitSelect(ctx, req.(*UnitSelectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "srspb.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitAuth",
			Handler:    _AuthService_InitAuth_Handler,
		},
		{
			MethodName: "DiscoverAuthenticationFlows",
			Handler:    _AuthService_DiscoverAuthenticationFlows_Handler,
		},
		{
			MethodName: "GuestLogin",
			Handler:    _AuthService_GuestLogin_Handler,
		},
		{
			MethodName: "StartAuth",
			Handler:    _AuthService_StartAuth_Handler,
		},
		{
			MethodName: "ContinueAuth",
			Handler:    _AuthService_ContinueAuth_Handler,
		},
		{
			MethodName: "UnitSelect",
			Handler:    _AuthService_UnitSelect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "srs.proto",
}

const (
	SRSService_SyncClient_FullMethodName         = "/srspb.SRSService/SyncClient"
	SRSService_UpdateClientInfo_FullMethodName   = "/srspb.SRSService/UpdateClientInfo"
	SRSService_UpdateRadioInfo_FullMethodName    = "/srspb.SRSService/UpdateRadioInfo"
	SRSService_Disconnect_FullMethodName         = "/srspb.SRSService/Disconnect"
	SRSService_GetServerSettings_FullMethodName  = "/srspb.SRSService/GetServerSettings"
	SRSService_Ping_FullMethodName               = "/srspb.SRSService/Ping"
	SRSService_SubscribeToUpdates_FullMethodName = "/srspb.SRSService/SubscribeToUpdates"
)

// SRSServiceClient is the client API for SRSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition
type SRSServiceClient interface {
	// Client synchronization request
	SyncClient(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SyncResponse, error)
	// Client update (metadata, client info)
	UpdateClientInfo(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (*ServerResponse, error)
	// Client radio update (metadata, radio info)
	UpdateRadioInfo(ctx context.Context, in *RadioInfo, opts ...grpc.CallOption) (*ServerResponse, error)
	// Client disconnect (metadata)
	Disconnect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServerResponse, error)
	// Server settings request
	GetServerSettings(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServerSettings, error)
	// Latency probe — client calls periodically and reports its measured RTT
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// Server-to-client updates stream
	SubscribeToUpdates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServerUpdate], error)
}

type sRSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSRSServiceClient(cc grpc.ClientConnInterface) SRSServiceClient {
	return &sRSServiceClient{cc}
}

func (c *sRSServiceClient) SyncClient(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, SRSService_SyncClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sRSServiceClient) UpdateClientInfo(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (*ServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerResponse)
	err := c.cc.Invoke(ctx, SRSService_UpdateClientInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sRSServiceClient) UpdateRadioInfo(ctx context.Context, in *RadioInfo, opts ...grpc.CallOption) (*ServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerResponse)
	err := c.cc.Invoke(ctx, SRSService_UpdateRadioInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sRSServiceClient) Disconnect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerResponse)
	err := c.cc.Invoke(ctx, SRSService_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sRSServiceClient) GetServerSettings(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServerSettings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerSettings)
	err := c.cc.Invoke(ctx, SRSService_GetServerSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sRSServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, SRSService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sRSServiceClient) SubscribeToUpdates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServerUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SRSService_ServiceDesc.Streams[0], SRSService_SubscribeToUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, ServerUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SRSService_SubscribeToUpdatesClient = grpc.ServerStreamingClient[ServerUpdate]

// SRSServiceServer is the server API for SRSService service.
// All implementations must embed UnimplementedSRSServiceServer
// for forward compatibility.
//
// Service definition
type SRSServiceServer interface {
	// Client synchronization request
	SyncClient(context.Context, *Empty) (*SyncResponse, error)
	// Client update (metadata, client info)
	UpdateClientInfo(context.Context, *ClientInfo) (*ServerResponse, error)
	// Client radio update (metadata, radio info)
	UpdateRadioInfo(context.Context, *RadioInfo) (*ServerResponse, error)
	// Client disconnect (metadata)
	Disconnect(context.Context, *Empty) (*ServerResponse, error)
	// Server settings request
	GetServerSettings(context.Context, *Empty) (*ServerSettings, error)
	// Latency probe — client calls periodically and reports its measured RTT
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// Server-to-client updates stream
	SubscribeToUpdates(*Empty, grpc.ServerStreamingServer[ServerUpdate]) error
	mustEmbedUnimplementedSRSServiceServer()
}

// UnimplementedSRSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSRSServiceServer struct{}

func (UnimplementedSRSServiceServer) SyncClient(context.Context, *Empty) (*SyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncClient not implemented")
}
func (UnimplementedSRSServiceServer) UpdateClientInfo(context.Context, *ClientInfo) (*ServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateClientInfo not implemented")
}
func (UnimplementedSRSServiceServer) UpdateRadioInfo(context.Context, *RadioInfo) (*ServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRadioInfo not implemented")
}
func (UnimplementedSRSServiceServer) Disconnect(context.Context, *Empty) (*ServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedSRSServiceServer) GetServerSettings(context.Context, *Empty) (*ServerSettings, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServerSettings not implemented")
}
func (UnimplementedSRSServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedSRSServiceServer) SubscribeToUpdates(*Empty, grpc.ServerStreamingServer[ServerUpdate]) error {
	return status.Error(codes.Unimplemented, "method SubscribeToUpdates not implemented")
}
func (UnimplementedSRSServiceServer) mustEmbedUnimplementedSRSServiceServer() {}
func (UnimplementedSRSServiceServer) testEmbeddedByValue()                    {}

// UnsafeSRSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SRSServiceServer will
// result in compilation errors.
type UnsafeSRSServiceServer interface {
	mustEmbedUnimplementedSRSServiceServer()
}

func RegisterSRSServiceServer(s grpc.ServiceRegistrar, srv SRSServiceServer) {
	// If the following call panics, it indicates UnimplementedSRSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SRSService_ServiceDesc, srv)
}

func _SRSService_SyncClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SRSServiceServer).SyncClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SRSService_SyncClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SRSServiceServer).SyncClient(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SRSService_UpdateClientInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SRSServiceServer).UpdateClientInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SRSService_UpdateClientInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SRSServiceServer).UpdateClientInfo(ctx, req.(*ClientInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _SRSService_UpdateRadioInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RadioInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SRSServiceServer).UpdateRadioInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SRSService_UpdateRadioInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SRSServiceServer).UpdateRadioInfo(ctx, req.(*RadioInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _SRSService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SRSServiceServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SRSService_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SRSServiceServer).Disconnect(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SRSService_GetServerSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SRSServiceServer).GetServerSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SRSService_GetServerSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SRSServiceServer).GetServerSettings(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SRSService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SRSServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SRSService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SRSServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SRSService_SubscribeToUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SRSServiceServer).SubscribeToUpdates(m, &grpc.GenericServerStream[Empty, ServerUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SRSService_SubscribeToUpdatesServer = grpc.ServerStreamingServer[ServerUpdate]

// SRSService_ServiceDesc is the grpc.ServiceDesc for SRSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SRSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "srspb.SRSService",
	HandlerType: (*SRSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncClient",
			Handler:    _SRSService_SyncClient_Handler,
		},
		{
			MethodName: "UpdateClientInfo",
			Handler:    _SRSService_UpdateClientInfo_Handler,
		},
		{
			MethodName: "UpdateRadioInfo",
			Handler:    _SRSService_UpdateRadioInfo_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _SRSService_Disconnect_Handler,
		},
		{
			MethodName: "GetServerSettings",
			Handler:    _SRSService_GetServerSettings_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _SRSService_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeToUpdates",
			Handler:       _SRSService_SubscribeToUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "srs.proto",
}
