name: Test
on:
  push:
    branches: ["main"]
  pull_request_target:

jobs:
  test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Install dependencies
        uses: ConorMacBride/install-package@v1
        with:
          apt: gcc libgtk-3-dev libwebkit2gtk-4.1-dev protobuf-compiler

      - name: Install Wails
        run: go install -v github.com/wailsapp/wails/v3/cmd/wails3@latest

      - name: Install Protoc Plugins
        run: |
          go install -v google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install -v google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Generate Protobuf files
        run: |
          mkdir -p srspb voicecontrolpb vcsauthpb
          protoc --go_out=./srspb --go_opt=paths=source_relative --go-grpc_out=./srspb --go-grpc_opt=paths=source_relative srs.proto
          protoc --go_out=./voicecontrolpb --go_opt=paths=source_relative --go-grpc_out=./voicecontrolpb --go-grpc_opt=paths=source_relative control.proto
          protoc --go_out=./vcsauthpb --go_opt=paths=source_relative --go-grpc_out=./vcsauthpb --go-grpc_opt=paths=source_relative vcs-auth-plugin.proto

      - name: Run tests
        run: go test -v -tags headless -coverprofile=coverage.out ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
        with:
          files: coverage.out
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
